Repository sopt-makers/sopt.org-frontend, pull requests merged in 2022-11, with the labels that each got.

#23 [FEAT] 프로젝트 디테일 뷰 모바일 헤더 반영 및 css 수정
  src/components/Footer/Footer.style.tsx
  src/components/Header/Header.tsx
  src/components/Header/MobileHeader/HeaderMenu.style.ts
  src/components/Header/MobileHeader/HeaderMenu.tsx
  src/components/Header/MobileHeader/MobileHeader.tsx
  src/components/Layout/Layout.tsx
  src/lib/styles/animation.ts
  src/views/ProjectDetailPage/ProjectDetail.style.tsx
  src/views/ProjectDetailPage/ProjectDetailPage.tsx
  src/views/ProjectDetailPage/components/UpButton.tsx
  src/views/ProjectDetailPage/constants/contants.ts
  src/views/ProjectDetailPage/types.ts
  src/views/ProjectDetailPage/utils/getLinkNameAndSrcWithType.ts
Labels: bug, feat

#26 [FEAT] API 변경사항 반영 및 break point 변경에 따른 UI 수정
  src/utils/dateFormat.ts
  src/views/ProjectDetailPage/ProjectDetail.style.tsx
  src/views/ProjectDetailPage/ProjectDetailPage.tsx
  src/views/ProjectDetailPage/components/UpButton.tsx
  src/views/ProjectDetailPage/types.ts
  src/views/ProjectDetailPage/utils/getLinkNameAndSrcWithType.ts
Labels: enhancement, feat

#27 Feat project lazy loading
  package.json
  pnpm-lock.yaml
  src/lib/project.ts
  src/pages/api/hello.ts
  src/views/ProjectPage/ProjectPage.tsx
  src/views/ProjectPage/assets/app-store-40x40.svg
  src/views/ProjectPage/assets/github-40x40.svg
  src/views/ProjectPage/assets/instagram-30x30.svg
  src/views/ProjectPage/assets/play-store-40x40.svg
  src/views/ProjectPage/assets/website-40x40.svg
  src/views/ProjectPage/assets/youtube-30x30.svg
  src/views/ProjectPage/components/DesktopFilter.tsx
  src/views/ProjectPage/components/MobileFilter.tsx
  src/views/ProjectPage/components/MobileFilterModal.tsx
  src/views/ProjectPage/components/ProjectCard.tsx
  src/views/ProjectPage/components/ProjectList.tsx
  src/views/ProjectPage/hooks/useFetch.ts
  src/views/ProjectPage/hooks/useScroll.ts
  src/views/ProjectPage/lib/constants.ts
  src/views/ProjectPage/styles/empty.module.scss
  src/views/ProjectPage/styles/project-card.module.scss
  src/views/ProjectPage/styles/project-enroll.module.scss
  src/views/ProjectPage/styles/project-list.module.scss
  src/views/ProjectPage/types.ts
Labels: feat

#34 디자인 QA 반영
  src/components/Header/MobileHeader/HeaderMenu.style.ts
  src/components/Header/MobileHeader/HeaderMenu.tsx
  src/components/Header/MobileHeader/MobileHeader.tsx
  src/constants/headerMenu.ts
  src/views/ProjectDetailPage/ProjectDetail.style.tsx
  src/views/ProjectDetailPage/ProjectDetailPage.tsx
  src/views/ProjectPage/ProjectPage.tsx
Labels: feat

#35 Fix plan design qa
  .github/workflows/ci.yml
  src/assets/icons/arrow-right-16x16.svg
  src/components/Footer/Footer.style.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/DesktopHeader.tsx
  src/lib/project.ts
  src/views/ProjectPage/ProjectPage.tsx
  src/views/ProjectPage/components/common/EmptyContent.tsx
  src/views/ProjectPage/components/filter/MobileFilterModal.tsx
  src/views/ProjectPage/components/project/ProjectList.tsx
  src/views/ProjectPage/components/project/project-list.module.scss
  src/views/ProjectPage/lib/constants.ts
Labels: feat

#37 Fix/#36 이미지 도메인 추가 및 LinkType 수정
  next.config.js
  src/views/ProjectDetailPage/types.ts
  src/views/ProjectDetailPage/utils/getLinkNameAndSrcWithType.ts
  src/views/ProjectPage/types.ts
Labels: size/M

#38 변경된 API 반영
  src/components/About/Seminar/PartInfos/PartInfos.tsx
  src/components/History/HistoryList/HistoryList.tsx
  src/components/Home/Introduce/IconBanner/IconBanner.tsx
  src/components/Partners/Partners/PartnerCard/PartnerCard.tsx
  src/components/Partners/Partners/Partners.tsx
  src/components/Partners/Projects/Projects.tsx
  src/lib/api.ts
Labels: feat

#40 feat: Design QA Header, Footer 반영
  src/components/Header/MobileHeader/HeaderMenu.tsx
  src/components/Header/MobileHeader/MobileHeader.tsx
  src/views/ProjectPage/components/project/ProjectCard.tsx
  src/views/ProjectPage/components/project/project-list.module.scss
Labels: size/S
