Repository sopt-makers/sopt.org-frontend, pull requests merged in 2022-10, with the labels that each got.

#4 불필요 모듈 제거, ESLint, Prettier 세팅 및 ESLint Warning에 해당되는 코드 제거
  .eslintrc.json
  changelog.config.js
  package.json
  pnpm-lock.yaml
  src/components/About/Seminar/PartInfo/PartInfo.style.tsx
  src/components/About/Seminar/PartInfos/PartInfos.style.tsx
  src/components/About/Seminar/PartInfos/PartInfos.tsx
  src/components/About/SoptTerm/SoptTerm.tsx
  src/components/About/Team/Team.tsx
  src/components/History/DetailMain/DetailMain.tsx
  src/components/History/HistoryList/HistoryList.tsx
  src/components/History/Sidebar/Sidebar.tsx
  src/components/Home/Introduce/IconBanner/IconBanner.tsx
  src/components/Home/Recruit/Recruit.tsx
  src/components/Partners/Partners/Partners.tsx
  src/components/Partners/Partners/PartnersSkeleton/PartnersSkeleton.tsx
  src/components/Partners/Projects/Projects.tsx
  src/components/common/BorderRoundButton/BorderRoundButton.tsx
  src/components/common/CommonError/CommonError.tsx
  src/components/common/ErrorBoundary/ErrorBoundary.tsx
  src/components/common/Footer/Channels/Channels.tsx
  src/components/common/Footer/Footer.style.tsx
  src/components/common/Footer/Footer.tsx
  src/components/common/Header/Header.test.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Header/Menu/HeaderMenu.tsx
  src/hooks/useMounted.ts
  src/pages/history/index.tsx
  src/pages/projects.tsx
  src/pages/recruit.tsx
  src/types/index.ts
Labels: enhancement

#5 Issue, Pull Request Template 작성
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactor-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  package.json
Labels: enhancement

#7 Feat/#6 프로젝트 디테일 뷰 UI 구현
  .gitignore
  package.json
  src/assets/icons/appstore_icon.svg
  src/assets/icons/github_icon.svg
  src/assets/icons/googleplay_icon.svg
  src/assets/icons/media_icon.svg
  src/assets/icons/upArrow.svg
  src/assets/icons/website_icon.svg
  src/assets/images/rightArrow.svg
  src/assets/images/toggle.svg
  src/assets/images/youtube_logo.svg
  src/components/Projects/ProjectDetail/ProjectDetail.style.tsx
  src/components/Projects/ProjectDetail/ProjectDetail.tsx
  src/components/Projects/ProjectDetail/index.tsx
  src/components/common/Header/Header.style.tsx
  src/lib/project.ts
  src/pages/projects.tsx
  src/styles/global.ts
  src/styles/globals.css
Labels: feat

#9 ProjectList 비지니스 로직 구성을 위한 작업 수행
  .eslintrc.json
  package.json
  pnpm-lock.yaml
  src/components/About/Appjam/AppjamBox/AppjamBox.tsx
  src/components/Partners/Partners/Partners.tsx
  src/components/common/Footer/Channels/Channels.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Header/Menu/HeaderMenu.tsx
  src/lib/components/Condition.tsx
  src/lib/index.ts
  src/pages/project.ts
  src/views/ProjectPage/ProjectPage.tsx
  src/views/ProjectPage/index.ts
  src/views/ProjectPage/mock.ts
  src/views/ProjectPage/reducer.ts
  src/views/ProjectPage/styles.ts
  src/views/ProjectPage/types.ts
Labels: enhancement, feat

#13 프로젝트 모바일 뷰 및 필터 기능 구현
  .eslintrc.json
  src/assets/icons/MobileFilterBtn.svg
  src/assets/icons/ToggleArrow.svg
  src/assets/icons/github_icon.svg
  src/assets/logo/website.svg
  src/components/common/Footer/Footer.style.tsx
  src/components/common/Header/Header.style.tsx
  src/styles/global.ts
  src/views/ProjectPage/ProjectPage.tsx
  src/views/ProjectPage/constants.ts
  src/views/ProjectPage/styles.module.scss
  src/views/ProjectPage/styles.ts
  src/views/ProjectPage/types.ts
Labels: enhancement, feat

#14 [FEAT] 프로젝트 디테일 뷰 PC 뷰
  src/components/ProjectHeader/ProjectHeader.style.tsx
  src/components/ProjectHeader/ProjectHeader.tsx
  src/components/ProjectHeader/index.tsx
  src/components/Projects/ProjectDetail/ProjectDetail.tsx
  src/components/Projects/ProjectDetail/index.tsx
  src/components/common/Footer/Footer.style.tsx
  src/components/common/Footer/Footer.tsx
  src/components/common/Header/Menu/HeaderMenu.style.tsx
  src/components/common/Header/Menu/HeaderMenu.tsx
  src/constants/headerMenu.ts
  src/pages/_app.tsx
  src/pages/project/[id]/index.ts
  src/pages/project/index.ts
  src/styles/font.css
  src/styles/fonts/SUIT-Bold.otf
  src/styles/fonts/SUIT-Bold.woff2
  src/styles/fonts/SUIT-ExtraBold.otf
  src/styles/fonts/SUIT-ExtraBold.woff2
  src/styles/fonts/SUIT-ExtraLight.otf
  src/styles/fonts/SUIT-ExtraLight.woff2
  src/styles/fonts/SUIT-Heavy.otf
  src/styles/fonts/SUIT-Heavy.woff2
  src/styles/fonts/SUIT-Light.otf
  src/styles/fonts/SUIT-Light.woff2
  src/styles/fonts/SUIT-Medium.otf
  src/styles/fonts/SUIT-Medium.woff2
  src/styles/fonts/SUIT-Regular.otf
  src/styles/fonts/SUIT-Regular.woff2
  src/styles/fonts/SUIT-SemiBold.otf
  src/styles/fonts/SUIT-SemiBold.woff2
  src/styles/fonts/SUIT-Thin.otf
  src/styles/fonts/SUIT-Thin.woff2
  src/styles/global.ts
  src/utils/dateFormat.ts
  src/utils/scrollDebounce.ts
  src/views/ProjectDetailPage/ProjectDetail.style.tsx
  src/views/ProjectDetailPage/ProjectDetailPage.tsx
  src/views/ProjectDetailPage/index.tsx
  src/views/ProjectPage/ProjectPage.tsx
Labels: enhancement, feat

#21 데스크탑 헤더 및 이슈 해결
  .github/ ISSUE_REQUEST_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/components/Footer/Channels/Channels.style.tsx
  src/components/Footer/Channels/Channels.tsx
  src/components/Footer/Channels/index.ts
  src/components/Footer/Footer.style.tsx
  src/components/Footer/Footer.tsx
  src/components/Footer/index.ts
  src/components/Header/DesktopHeader.tsx
  src/components/Header/Header.tsx
  src/components/Header/MobileHeader/HeaderMenu.style.ts
  src/components/Header/MobileHeader/HeaderMenu.tsx
  src/components/Header/MobileHeader/MobileHeader.tsx
  src/components/Header/index.ts
  src/components/Layout/Layout.tsx
  src/components/Layout/index.ts
  src/components/ProjectHeader/ProjectHeader.style.tsx
  src/components/ProjectHeader/ProjectHeader.tsx
  src/components/ProjectHeader/index.tsx
  src/components/common/Footer/index.ts
  src/components/common/Header/Header.style.tsx
  src/components/common/Header/Header.test.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Header/Menu/index.tsx
  src/components/common/Header/index.tsx
  src/components/index.ts
  src/pages/404.tsx
  src/pages/_app.tsx
  src/pages/about.tsx
  src/pages/history/[id]/index.tsx
  src/pages/history/index.tsx
  src/pages/index.tsx
  src/pages/partners.tsx
  src/pages/recruit.tsx
  src/pages/rules.tsx
  src/styles/globals.css
  src/views/ProjectDetailPage/ProjectDetail.style.tsx
  src/views/ProjectDetailPage/ProjectDetailPage.tsx
  src/views/ProjectPage/ProjectPage.tsx
  src/views/ProjectPage/components/DesktopFilter.tsx
  src/views/ProjectPage/components/EmptyContent.tsx
  src/views/ProjectPage/components/MobileFilter.tsx
  src/views/ProjectPage/components/MobileFilterModal.tsx
  src/views/ProjectPage/components/MobileUtilityButtons.tsx
  src/views/ProjectPage/components/Project.tsx
  src/views/ProjectPage/components/ProjectEnrollSection.tsx
  src/views/ProjectPage/components/ProjectList.tsx
  src/views/ProjectPage/components/index.ts
  src/views/ProjectPage/lib/constants.ts
  src/views/ProjectPage/lib/reducer.ts
  src/views/ProjectPage/styles.module.scss
  src/views/ProjectPage/styles/desktop-filter.module.scss
  src/views/ProjectPage/styles/empty.module.scss
  src/views/ProjectPage/styles/mobile-filter.module.scss
  src/views/ProjectPage/styles/project-enroll.module.scss
  src/views/ProjectPage/styles/project-list.module.scss
  src/views/ProjectPage/styles/project.module.scss
Labels: bug, feat
