Repository sopt-makers/sopt.org-frontend, pull requests merged in 2023-11, with the labels that each got.

#258 [SP2]프로젝트 캐러셀 SkeletonUI
  src/views/ProjectPage/components/RecentProjectList/Item/style.ts
  src/views/ProjectPage/components/RecentProjectList/RecentProjectListSkeletonUI/index.tsx
  src/views/ProjectPage/components/RecentProjectList/RecentProjectListSkeletonUI/style.ts
  src/views/ProjectPage/components/RecentProjectList/index.tsx
Labels: size/L

#251 [SP2] 블로그 페이지 스켈레톤 UI, scrollToTop, react-query
  src/lib/api/remote/review.ts
  src/lib/api/remote/sopticle.ts
  src/lib/types/blog.ts
  src/lib/types/review.ts
  src/lib/types/sopticle.ts
  src/views/BlogPage/BlogPage.tsx
  src/views/BlogPage/components/BlogPost/style.ts
  src/views/BlogPage/components/BlogPostList/index.tsx
  src/views/BlogPage/components/BlogPostList/style.ts
  src/views/BlogPage/components/BlogPostSkeletonUI/index.tsx
  src/views/BlogPage/components/BlogPostSkeletonUI/style.ts
  src/views/BlogPage/components/BlogTab/style.ts
  src/views/BlogPage/hooks/queries/useGetResponse.ts
  src/views/BlogPage/hooks/useFetch.ts
  src/views/BlogPage/hooks/useInfiniteScroll.ts
  src/views/BlogPage/style.ts
Labels: size/XL

#254 [SP2] 프로젝트 서비스 이용 가능 및 창업중 정보 보여주기
  src/assets/icons/ic_ellipse_green.svg
  src/views/ProjectPage/components/project/ProjectCard/ServiceInfo/index.tsx
  src/views/ProjectPage/components/project/ProjectCard/ServiceInfo/style.ts
  src/views/ProjectPage/components/project/ProjectCard/index.tsx
  src/views/ProjectPage/components/project/ProjectCard/style.ts
Labels: size/M

#256 [SP2] 프로젝트 목록 useQuery 적용 및 필터링 값 유지
  src/lib/api/remote/project.ts
  src/lib/types/project.ts
  src/pages/_app.tsx
  src/views/BlogPage/components/BlogPost/index.tsx
  src/views/ProjectPage/ProjectPage.tsx
  src/views/ProjectPage/components/RecentProjectList/Item/style.ts
  src/views/ProjectPage/components/RecentProjectList/RecentProjectListSkeletonUI/index.tsx
  src/views/ProjectPage/components/RecentProjectList/RecentProjectListSkeletonUI/style.ts
  src/views/ProjectPage/components/RecentProjectList/index.tsx
  src/views/ProjectPage/components/project/ProjectCard/index.tsx
  src/views/ProjectPage/components/project/ProjectCard/style.ts
  src/views/ProjectPage/components/project/ProjectCardList/index.tsx
  src/views/ProjectPage/components/project/ProjectCardList/style.ts
  src/views/ProjectPage/components/project/ProjectList.tsx
  src/views/ProjectPage/components/project/ProjectListCount/index.tsx
  src/views/ProjectPage/components/project/ProjectListCount/style.ts
  src/views/ProjectPage/components/project/ProjectListFallback/ProjectCardSkeletonUI/index.tsx
  src/views/ProjectPage/components/project/ProjectListFallback/ProjectCardSkeletonUI/style.ts
  src/views/ProjectPage/components/project/ProjectListFallback/index.tsx
  src/views/ProjectPage/components/project/ProjectListFallback/style.ts
  src/views/ProjectPage/components/project/style.ts
  src/views/ProjectPage/hooks/queries/index.ts
  src/views/ProjectPage/hooks/useFetch.ts
  src/views/ProjectPage/hooks/useInfiniteScroll.ts
  src/views/ProjectPage/styles.ts
Labels: size/XL

#260 [SP2] 블로그 페이지 Suspense 적용
  src/pages/_app.tsx
  src/views/BlogPage/BlogPage.tsx
  src/views/BlogPage/components/BlogPost/Header/index.tsx
  src/views/BlogPage/components/BlogPost/index.tsx
  src/views/BlogPage/components/BlogPostList/index.tsx
  src/views/BlogPage/components/BlogPostList/style.ts
  src/views/BlogPage/components/BlogTab/index.tsx
  src/views/BlogPage/components/BlogTab/types.ts
  src/views/BlogPage/components/EmptyBlogPostList/index.tsx
  src/views/BlogPage/components/EmptyBlogPostList/style.ts
  src/views/BlogPage/hooks/queries/useGetResponse.ts
  src/views/ProjectPage/hooks/queries/index.ts
Labels: size/L

#262 [SP2] 프로젝트 카드 디자인 수정
  src/views/ProjectPage/components/project/ProjectCard/style.ts
Labels: size/XS

#264 [SP2] 블로그, 프로젝트 QA
  src/assets/icons/chevronDown.svg
  src/components/common/Select/index.tsx
  src/components/common/Select/style.ts
  src/views/BlogPage/components/BlogPost/Like/style.ts
  src/views/ProjectPage/components/RecentProjectList/index.tsx
  src/views/ProjectPage/styles.ts
Labels: size/L

#266 [SP2] 프로젝트 탭 캐러셀 블러 스타일 수정
  src/components/common/Carousel/index.tsx
  src/components/common/Carousel/style.ts
  src/views/ProjectPage/components/RecentProjectList/Carousel/index.tsx
  src/views/ProjectPage/components/RecentProjectList/Item/style.ts
Labels: size/M

#268 [SP2] CI 에러 고치기, 리크루팅 탭 활동후기 복원
  src/views/BlogPage/hooks/useInfiniteScroll.ts
  src/views/RecruitPage/components/ActivityReview/index.tsx
Labels: size/S

#270 [SP2] 모바일에서도 프로젝트 탭 캐러셀의 화살표가 보여 깨지는 현상 수정
  src/components/common/Carousel/style.ts
Labels: size/XS

#277 [SP2/hotfix] 하이드레이션 에러 해결
  src/components/common/Carousel/style.ts
  src/views/ProjectPage/components/RecentProjectList/Carousel/index.tsx
  src/views/ProjectPage/components/RecentProjectList/Item/style.ts
  src/views/ProjectPage/components/RecentProjectList/RecentProjectListSkeletonUI/index.tsx
  src/views/ProjectPage/components/RecentProjectList/RecentProjectListSkeletonUI/style.ts
  src/views/ProjectPage/components/RecentProjectList/index.tsx
  src/views/ProjectPage/styles.ts
Labels: size/L

#278 [SP2]블로그 모바일 탭 css 추가
  src/views/BlogPage/components/BlogTab/style.ts
Labels: size/XS

#275 [SP2] 프로젝트 탭 디자인 일부 수정
  src/components/common/Carousel/index.tsx
  src/components/common/Carousel/style.ts
  src/components/common/Select/index.tsx
  src/components/common/Select/style.ts
  src/lib/constants/project.ts
  src/lib/types/universal.ts
  src/views/BlogPage/components/BlogTab/index.tsx
  src/views/BlogPage/components/BlogTab/style.ts
  src/views/ProjectPage/ProjectPage.tsx
  src/views/ProjectPage/components/RecentProjectList/Carousel/index.tsx
  src/views/ProjectPage/components/project/ProjectCard/style.ts
  src/views/ProjectPage/styles.ts
Labels: size/L

#280 [SP2] blog 페이지 url 주소 작업
  next.config.js
Labels: size/S

#285 [SP2] 메인페이지 와앙 솝트 로고 작업
  package.json
  pnpm-lock.yaml
  src/assets/icons/ic_logo_sopt_white.svg
  src/components/common/DummyDiv/index.tsx
  src/views/MainPage/MainPage.tsx
  src/views/MainPage/components/ScrollInteractiveLogo/index.tsx
  src/views/MainPage/components/ScrollInteractiveLogo/style.ts
Labels: size/L

#282 [SP2] 메인 페이지에서 그림자가 마우스를 따라다니는 리크루팅 버튼 구현
  src/lib/styles/animation.ts
  src/views/MainPage/components/Banner/RecruitButton/index.tsx
  src/views/MainPage/components/Banner/RecruitButton/style.ts
  src/views/MainPage/components/Banner/index.tsx
  src/views/MainPage/components/Banner/style.ts
Labels: size/L

#288 [SP2] 메인페이지 상단 두번째 섹션 애니메이션
  package-lock.json
  src/views/MainPage/components/Introduce/MotionTitle/index.tsx
  src/views/MainPage/components/Introduce/MotionTitle/style.ts
  src/views/MainPage/components/Introduce/index.tsx
  src/views/MainPage/components/Introduce/style.ts
Labels: size/L

#292 [SP2] 메인 상단 Introduce QA
  src/views/MainPage/components/Introduce/MotionTitle/index.tsx
  src/views/MainPage/components/Introduce/MotionTitle/style.ts
  src/views/MainPage/components/Introduce/index.tsx
  src/views/MainPage/components/Introduce/style.ts
Labels: size/M

#299 [SP2] 메인 가치 섹션 QA
  src/views/MainPage/components/IntroSection/IntroContent/index.tsx
  src/views/MainPage/components/IntroSection/IntroContent/style.ts
Labels: size/XS

#297 [SP2] 메인페이지 모집알림신청 버튼 QA
  src/views/MainPage/components/Banner/RecruitButton/index.tsx
  src/views/MainPage/components/Banner/RecruitButton/style.ts
Labels: size/M

#301 [SP2] 릴리즈 소식 알리기 링크 변경
  src/views/ProjectPage/components/RecentProjectList/index.tsx
Labels: size/XS
