Repository sopt-makers/sopt.org-frontend, pull requests merged in 2023-01, with the labels that each got.

#47 feat/#46: serviceType 웹,앱 이슈 수정
  src/views/ProjectDetailPage/ProjectDetailPage.tsx
Labels: size/XS

#48 Remove legacy main page
  package.json
  pnpm-lock.yaml
  src/assets/replaceMe/imageList.ts
  src/components/Home/Branding/Branding.style.tsx
  src/components/Home/Branding/Branding.tsx
  src/components/Home/Branding/Symbol/Symbol.style.tsx
  src/components/Home/Branding/Symbol/Symbol.tsx
  src/components/Home/Branding/Symbol/index.ts
  src/components/Home/Branding/index.ts
  src/components/Home/Events/DetailInfo/DetailInfo.style.tsx
  src/components/Home/Events/DetailInfo/DetailInfo.tsx
  src/components/Home/Events/DetailInfo/index.ts
  src/components/Home/Events/Event/Event.style.tsx
  src/components/Home/Events/Event/Event.tsx
  src/components/Home/Events/Event/index.ts
  src/components/Home/Events/Events.style.tsx
  src/components/Home/Events/Events.tsx
  src/components/Home/Events/index.ts
  src/components/Home/Introduce/Description/Description.style.tsx
  src/components/Home/Introduce/Description/Description.tsx
  src/components/Home/Introduce/Description/index.tsx
  src/components/Home/Introduce/IconBanner/IconBanner.style.tsx
  src/components/Home/Introduce/IconBanner/IconBanner.tsx
  src/components/Home/Introduce/IconBanner/index.tsx
  src/components/Home/Introduce/Introduce.style.tsx
  src/components/Home/Introduce/Introduce.tsx
  src/components/Home/Introduce/index.tsx
  src/components/Home/Recruit/Recruit.style.tsx
  src/components/Home/Recruit/Recruit.tsx
  src/components/Home/Recruit/index.ts
  src/components/Home/SoptMarquee/SoptMarquee.style.tsx
  src/components/Home/SoptMarquee/SoptMarquee.tsx
  src/components/Home/SoptMarquee/index.ts
  src/components/Home/Top/Top.style.tsx
  src/components/Home/Top/Top.tsx
  src/components/Home/Top/index.tsx
  src/pages/index.tsx
Labels: size/XXL

#50 문의하기 페이지 구현
  src/assets/images/toggle.svg
  src/components/Header/Header.tsx
  src/hooks/useIsDesktop.ts
  src/pages/FAQ.tsx
  src/pages/_app.tsx
  src/styles/global.ts
  src/styles/globals.css
  src/views/FAQPage/FAQPage.tsx
  src/views/FAQPage/components/contact/ContactInfo.tsx
  src/views/FAQPage/components/contact/index.tsx
  src/views/FAQPage/components/faq/QuestionBox.tsx
  src/views/FAQPage/components/faq/index.tsx
  src/views/FAQPage/index.tsx
  src/views/FAQPage/lib/constants.ts
  src/views/FAQPage/types/index.ts
  src/views/ProjectDetailPage/ProjectDetailPage.tsx
  src/views/ProjectDetailPage/lib/contants.ts
Labels: size/XL

#53 Feat main page desktop design guide
  src/components/common/ScrollToTopButton/ScrollToTopButton.tsx
  src/components/common/ScrollToTopButton/index.ts
  src/components/index.ts
  src/views/MainPage/MainPage.tsx
  src/views/MainPage/assets/arrow-down.svg
  src/views/MainPage/assets/arrow-left-28x28.svg
  src/views/MainPage/assets/arrow-left.svg
  src/views/MainPage/assets/arrow-right-28x28.svg
  src/views/MainPage/components/ActivityDescription/ActivityDescription.tsx
  src/views/MainPage/components/ActivityDescription/activity-description.module.scss
  src/views/MainPage/components/BannerImage/BannerImage.tsx
  src/views/MainPage/components/BannerImage/banner-image.module.scss
  src/views/MainPage/components/CorporateLinkedActivities/CorporateLinkedActivities.tsx
  src/views/MainPage/components/CorporateLinkedActivities/corporate-linked-activities.module.scss
  src/views/MainPage/components/CorporatePartner/CorporatePartner.tsx
  src/views/MainPage/components/CorporatePartner/corporate-partner.module.scss
  src/views/MainPage/components/DetailedInformation/detailed-information.module.scss
  src/views/MainPage/components/PartDescription/PartDescription.tsx
  src/views/MainPage/components/PartDescription/part-description.module.scss
  src/views/MainPage/components/SoptHistory/sopt-history.module.scss
  src/views/MainPage/lib/index.ts
  src/views/MainPage/lib/useHorizontalScroll.ts
  src/views/MainPage/main-page.module.scss
  src/views/ProjectDetailPage/components/UpButton.tsx
Labels: size/XXL

#54 fix: corporate linked activities 제목 왼쪽맞춤 적용
  src/views/MainPage/components/CorporateLinkedActivities/CorporateLinkedActivities.tsx
  src/views/MainPage/components/CorporateLinkedActivities/corporate-linked-activities.module.scss
Labels: size/XS

#55 메인 페이지 기획 QA 반영 및 누락된 디자인 가이드 반영
  src/hooks/useIsDesktop.ts
  src/views/MainPage/components/ActivityDescription/ActivityDescription.tsx
  src/views/MainPage/components/ActivityDescription/activity-description.module.scss
  src/views/MainPage/components/BannerImage/BannerImage.tsx
  src/views/MainPage/components/CorporateLinkedActivities/CorporateLinkedActivities.tsx
  src/views/MainPage/components/CorporateLinkedActivities/constants.ts
  src/views/MainPage/components/CorporateLinkedActivities/corporate-linked-activities.module.scss
  src/views/MainPage/components/CorporatePartner/CorporatePartner.tsx
  src/views/MainPage/components/CorporatePartner/corporate-partner.module.scss
  src/views/MainPage/components/DetailedInformation/detailed-information.module.scss
  src/views/MainPage/components/PartDescription/PartDescription.tsx
  src/views/MainPage/components/PartDescription/part-description.module.scss
Labels: feat, size/L

#56 Hotfix main page design guide
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Header/header.module.scss
  src/components/common/ScrollToTopButton/ScrollToTopButton.tsx
  src/components/common/ScrollToTopButton/scroll-to-top-button.module.scss
  src/hooks/useDevice.ts
  src/pages/404.tsx
  src/views/FAQPage/components/faq/index.tsx
  src/views/MainPage/components/ActivityDescription/ActivityDescription.tsx
  src/views/MainPage/components/PartDescription/PartDescription.tsx
  src/views/ProjectDetailPage/ProjectDetailPage.tsx
  src/views/ProjectDetailPage/components/UpButton.tsx
  src/views/ProjectDetailPage/lib/contants.ts
  src/views/ProjectPage/ProjectPage.tsx
  src/views/ProjectPage/components/filter/DesktopFilter.tsx
  src/views/ProjectPage/components/filter/MobileFilter.tsx
  src/views/ProjectPage/components/filter/MobileUtilityButton.tsx
  src/views/ProjectPage/components/filter/ProjectFilter.tsx
  src/views/ProjectPage/components/filter/mobile-utility-button.module.scss
  src/views/ProjectPage/components/project/ProjectCard.tsx
  src/views/ProjectPage/components/utility/DesktopUtilityButtons.tsx
  src/views/ProjectPage/components/utility/utility.module.scss
  src/views/RulesPage/Rules.tsx
Labels: size/XL

#58 Project Detail Page 상단부 UI 깨짐현상 해결
  src/components/Header/Desktop/DesktopHeader.tsx
  src/views/ProjectDetailPage/ProjectDetail.style.tsx
  src/views/ProjectDetailPage/ProjectDetailPage.tsx
Labels: bug, size/L

#59 merge develop into main
  src/components/Header/Desktop/DesktopHeader.tsx
  src/views/ProjectDetailPage/ProjectDetail.style.tsx
  src/views/ProjectDetailPage/ProjectDetailPage.tsx
Labels: size/L

#60 useDevice hook들의 초기값을 false로 변경
  src/hooks/useDevice.ts
Labels: bug, size/XS

#61 merge develop into main
  src/hooks/useDevice.ts
Labels: size/XS

#62 fix: 문의하기 페이지 깨짐 해결
  src/hooks/useDevice.ts
  src/pages/_app.tsx
  src/views/FAQPage/FAQPage.tsx
  src/views/FAQPage/components/contact/ContactInfo.tsx
  src/views/FAQPage/components/contact/index.tsx
  src/views/FAQPage/components/faq/QuestionBox.tsx
  src/views/FAQPage/components/faq/index.tsx
Labels: size/M

#63 Merge develop into main
  src/hooks/useDevice.ts
  src/pages/_app.tsx
  src/views/FAQPage/FAQPage.tsx
  src/views/FAQPage/components/contact/ContactInfo.tsx
  src/views/FAQPage/components/contact/index.tsx
  src/views/FAQPage/components/faq/QuestionBox.tsx
  src/views/FAQPage/components/faq/index.tsx
Labels: size/M

#64 프로젝트 디테일 뷰 인스타그램 아이콘 크기 수정 및 콘솔 삭제
  src/assets/icons/github_icon.svg
  src/assets/icons/instagram_icon.svg
  src/assets/icons/youtube_icon.svg
  src/assets/logo/instagram.svg
  src/views/FAQPage/components/faq/index.tsx
  src/views/ProjectDetailPage/ProjectDetail.style.tsx
  src/views/ProjectDetailPage/ProjectDetailPage.tsx
  src/views/ProjectDetailPage/utils/getLinkNameAndSrcWithType.ts
Labels: size/S

#65 Merge develop into main
  src/assets/icons/github_icon.svg
  src/assets/icons/instagram_icon.svg
  src/assets/icons/youtube_icon.svg
  src/assets/logo/instagram.svg
  src/views/FAQPage/components/faq/index.tsx
  src/views/ProjectDetailPage/ProjectDetail.style.tsx
  src/views/ProjectDetailPage/ProjectDetailPage.tsx
  src/views/ProjectDetailPage/utils/getLinkNameAndSrcWithType.ts
Labels: size/S

#66 메인화면 슬로건 텍스트 위치 수정
  src/views/MainPage/components/BannerImage/banner-image.module.scss
Labels: size/XS

#67 Merge develop into main
  src/views/MainPage/components/BannerImage/banner-image.module.scss
Labels: size/XS

#68 메인페이지 Desktop 스타일 수정
  src/components/Header/Desktop/DesktopHeader.tsx
  src/components/Header/Header.tsx
  src/components/common/ScrollToTopButton/scroll-to-top-button.module.scss
  src/views/MainPage/MainPage.tsx
  src/views/MainPage/components/ActivityDescription/ActivityDescription.tsx
  src/views/MainPage/components/ActivityDescription/activity-description.module.scss
  src/views/MainPage/components/BannerImage/banner-image.module.scss
  src/views/MainPage/components/CorporateLinkedActivities/corporate-linked-activities.module.scss
  src/views/MainPage/components/CorporatePartner/corporate-partner.module.scss
  src/views/MainPage/components/DetailedInformation/detailed-information.module.scss
  src/views/MainPage/components/PartDescription/PartDescription.tsx
  src/views/MainPage/components/PartDescription/part-description.module.scss
  src/views/MainPage/components/SoptHistory/sopt-history.module.scss
  src/views/MainPage/main-page.module.scss
  src/views/MainPage/stylesheets/_mixins.scss
  src/views/MainPage/stylesheets/_variables.scss
Labels: feat, size/L

#69 메인 페이지 내 컴포넌트간 gap을 포함한 스타일 수정
  src/views/MainPage/components/BannerImage/banner-image.module.scss
  src/views/MainPage/components/CorporateLinkedActivities/corporate-linked-activities.module.scss
  src/views/MainPage/main-page.module.scss
Labels: feat, size/XS
