Repository sopt-makers/sopt.org-frontend, pull requests merged in 2023-09, with the labels that each got.

#158 fix: project description's white-space
  src/views/ProjectDetailPage/ProjectDetail.style.tsx
Labels: size/XS

#157 [SP0] Recruit 탭 추가
  package.json
  pnpm-lock.yaml
  src/assets/icons/ic_arrow_right_white.svg
  src/assets/icons/ic_email.svg
  src/assets/icons/ic_facebook.svg
  src/assets/icons/ic_kakao.svg
  src/assets/icons/img_instagram.png
  src/assets/images/img_mainvalue_logos.png
  src/assets/mainLogo/index.ts
  src/assets/mainLogo/logo_dosopt.png
  src/assets/mainLogo/logo_dosopt@2x.png
  src/assets/mainLogo/logo_dosopt@3x.png
  src/components/Header/Desktop/DesktopHeader.tsx
  src/components/Header/menuTapList.ts
  src/components/Layout/Layout.tsx
  src/pages/api/register.ts
  src/pages/recruit.tsx
  src/utils/const/googlesheet-env.ts
  src/views/FAQPage/components/faq/QuestionBox.tsx
  src/views/FAQPage/lib/constants.ts
  src/views/MainPage/assets/arrow_right_white.svg
  src/views/ProjectDetailPage/ProjectDetail.style.tsx
  src/views/RecruitPage/RecruitPage.tsx
  src/views/RecruitPage/components/ActivityReview/ActivityReview.tsx
  src/views/RecruitPage/components/ActivityReview/hooks/useFetch.ts
  src/views/RecruitPage/components/ActivityReview/styles.ts
  src/views/RecruitPage/components/ActivityReview/utils/parsePartToKorean.ts
  src/views/RecruitPage/components/ApplySection/index.tsx
  src/views/RecruitPage/components/BottomLogo/index.tsx
  src/views/RecruitPage/components/ChapterInfo/constants.ts
  src/views/RecruitPage/components/ChapterInfo/index.tsx
  src/views/RecruitPage/components/Contact/constant.ts
  src/views/RecruitPage/components/Contact/index.tsx
  src/views/RecruitPage/components/FAQ/constant.ts
  src/views/RecruitPage/components/FAQ/index.tsx
  src/views/RecruitPage/components/NotificationSection/index.tsx
  src/views/RecruitPage/components/RecruteeInfo/index.tsx
  src/views/RecruitPage/components/Schedule/index.tsx
  src/views/RecruitPage/components/common/Tabs/index.tsx
  src/views/RecruitPage/components/common/Tabs/style.ts
  src/views/RecruitPage/components/common/styles.ts
  src/views/RecruitPage/index.ts
Labels: size/XXL

#167 [SP0] 프로젝트 링크 넘침 이슈
  src/views/ProjectPage/components/project/ProjectCard.tsx
Labels: size/XS

#166 [SP0] 프로젝트 이미지 눌림 이슈
  src/views/ProjectPage/components/project/ProjectCard.tsx
  src/views/ProjectPage/components/project/project-card.module.scss
Labels: size/S

#175 [SP1] 솝티클 썸네일 이미지 찌부 이슈
  src/views/MainPage/components/ActivityDescription/ActivityDescription.tsx
  src/views/SopticlePage/components/Sopticles/style.ts
Labels: size/S

#178 [SP0] 리크루팅 배너와 지원 버튼 가리기, 리크루팅 탭 알림 버튼 변경, 디벨롭 브랜치에서 누락된 사항 추가
  package.json
  pnpm-lock.yaml
  src/views/MainPage/MainPage.tsx
  src/views/RecruitPage/RecruitPage.tsx
  src/views/RecruitPage/components/BottomLogo/index.tsx
  src/views/RecruitPage/components/NotificationSection/index.tsx
Labels: size/L

#187 [SP1] 솝트 회칙 페이지 컬러 변경
  src/views/RulesPage/components/UnderlinedText/UnderlinedText.style.tsx
Labels: size/XS

#182 [SP1] img 태그로 쓰인 이미지를 모두 next/image의 Image 컴포넌트로 변경
  src/components/corporate/JobPostingCard/index.tsx
  src/components/corporate/JobPostingCard/style.ts
  src/views/MainPage/components/ActivityReview/ActivityReview.tsx
  src/views/MainPage/components/ActivityReview/activity-review.module.scss
  src/views/MainPage/components/DetailedInformation/DetailedInformation.tsx
  src/views/MainPage/components/DetailedInformation/detailed-information.module.scss
  src/views/MainPage/components/RecruitFloatingBanner/RecruitFloatingBanner.tsx
  src/views/ProjectPage/components/project/ProjectCard.tsx
  src/views/ProjectPage/components/project/project-card.module.scss
  src/views/RecruitPage/components/ActivityReview/ActivityReview.tsx
  src/views/RecruitPage/components/ActivityReview/styles.ts
Labels: size/M

#188 [SP1] SEO 향상을 위한 meta tag, open graph
  src/components/Footer/Channels/index.tsx
  src/components/Header/Mobile/MobileHeader.tsx
  src/components/corporate/JobPostingCard/index.tsx
  src/lib/utils/parsePartToKorean.ts
  src/pages/404.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/views/AboutPage/components/Banner/index.tsx
  src/views/AboutPage/components/Cirriculum/Content/index.tsx
  src/views/AboutPage/components/Member/Card/index.tsx
  src/views/MainPage/components/ActivityDescription/ActivityDescription.tsx
  src/views/MainPage/components/ActivityReview/ActivityReview.tsx
  src/views/MainPage/components/BannerImage/BannerImage.tsx
  src/views/MainPage/components/DetailedInformation/DetailedInformation.tsx
  src/views/ProjectDetailPage/ProjectDetailPage.tsx
  src/views/ProjectPage/components/project/ProjectCard.tsx
  src/views/RecruitPage/components/ActivityReview/ActivityReview.tsx
  src/views/RecruitPage/components/ActivityReview/utils/parsePartToKorean.ts
  src/views/RecruitPage/components/BottomLogo/index.tsx
  src/views/RecruitPage/components/ChapterInfo/index.tsx
  src/views/RecruitPage/components/Contact/index.tsx
  src/views/SponsorPage/components/CorporateLinkedActivities/index.tsx
  src/views/StudyPage/components/Item/index.tsx
Labels: size/L

#196 [SP1]SOPT 회칙 수정
  src/lib/constants/rules.ts
Labels: size/XS

#193 [SP1] 리크루팅 알림받기 API에서 500 에러가 나는 것을 해결한다.
  src/lib/constants/googlesheet-env.ts
  src/pages/api/register.ts
Labels: size/XS

#189 [SP1] Amplitude 설정
  package.json
  pnpm-lock.yaml
  src/lib/constants/client.ts
  src/pages/_app.tsx
  src/utils/pageViewTrackingEnrichment.ts
  src/views/MainPage/components/ActivityDescription/ActivityDescription.tsx
  src/views/MainPage/components/PartDescription/PartDescription.tsx
  src/views/ReviewPage/components/TabBar/index.tsx
Labels: size/L

#199 [SP1] 리쿠르팅, 후원페이지 amplitude tracking code 심기
  src/views/RecruitPage/components/ActivityReview/ActivityReview.tsx
  src/views/RecruitPage/components/ChapterInfo/index.tsx
  src/views/RecruitPage/components/FAQ/index.tsx
  src/views/RecruitPage/components/NotificationSection/index.tsx
  src/views/RecruitPage/components/common/Tabs/index.tsx
  src/views/SponsorPage/components/CorporateJob/FieldTabs/index.tsx
  src/views/SponsorPage/components/CorporateJob/JobPostings/index.tsx
  src/views/SponsorPage/components/CorporateLinkedActivities/index.tsx
  src/views/SponsorPage/components/CorporatePartner/index.tsx
Labels: size/L

#202 [SP1] 앰플리튜드 이벤트 트래킹 - 메인페이지, 활동후기, 프로젝트
  src/views/MainPage/components/ActivityReview/ActivityReview.tsx
  src/views/MainPage/components/DetailedInformation/DetailedInformation.tsx
  src/views/ProjectPage/components/project/ProjectCard.tsx
  src/views/ReviewPage/components/Content/index.tsx
  src/views/ReviewPage/components/Reviews/index.tsx
Labels: size/S

#204 [SP1] 앰플리튜드 오타 수정
  src/views/SponsorPage/components/CorporatePartner/index.tsx
Labels: size/XS
