Repository sopt-makers/sopt.org-frontend, pull requests merged in 2023-04, with the labels that each got.

#97 Declare pnpm version for CI
  .github/workflows/ci.yml
Labels: size/XS

#99 chore: no frozen lockfile
  .github/workflows/ci.yml
Labels: size/XS

#102 만든 사람들 & 의견 제안하기
  src/components/Footer/Channels/index.ts
  src/components/Footer/Channels/index.tsx
  src/components/Footer/Channels/style.ts
  src/components/Footer/Footer.tsx
  src/components/Footer/MakersNForm/index.tsx
  src/components/Footer/MakersNForm/style.ts
  src/components/Footer/OriginFooter/index.tsx
  src/components/Footer/OriginFooter/style.ts
  src/hooks/useScrollPosition.ts
Labels: size/L

#104 Main from Develop
  src/components/Footer/Channels/index.ts
  src/components/Footer/Channels/index.tsx
  src/components/Footer/Channels/style.ts
  src/components/Footer/Footer.tsx
  src/components/Footer/MakersNForm/index.tsx
  src/components/Footer/MakersNForm/style.ts
  src/components/Footer/OriginFooter/index.tsx
  src/components/Footer/OriginFooter/style.ts
  src/hooks/useScrollPosition.ts
Labels: size/L

#105 #103 next13
  .babelrc
  package.json
  pnpm-lock.yaml
  src/components/Footer/Channels/index.tsx
  src/components/Footer/MakersNForm/style.ts
  src/components/Header/Desktop/DesktopHeader.tsx
  src/components/Header/Mobile/HeaderMenu.style.ts
  src/components/Header/Mobile/HeaderMenu.tsx
  src/components/Header/Mobile/MobileHeader.tsx
  src/pages/404.tsx
  src/pages/recruit.tsx
  src/views/MainPage/components/ActivityDescription/ActivityDescription.tsx
  src/views/MainPage/components/ActivityDescription/activity-description.module.scss
  src/views/MainPage/components/BannerImage/BannerImage.tsx
  src/views/MainPage/components/BannerImage/banner-image.module.scss
  src/views/MainPage/components/CorporateLinkedActivities/CorporateLinkedActivities.tsx
  src/views/MainPage/components/CorporatePartner/CorporatePartner.tsx
  src/views/MainPage/components/CorporatePartner/corporate-partner.module.scss
  src/views/ProjectDetailPage/ProjectDetailPage.tsx
  src/views/ReviewPage/components/Reviews/index.tsx
  src/views/ReviewPage/components/Reviews/style.ts
Labels: size/XL

#108 헤더 레이아웃 수정
  src/components/Header/Desktop/DesktopHeader.tsx
  src/components/Header/header.module.scss
Labels: size/XS

#86 refactor: give base url based on node environment
  src/lib/api.ts
  src/lib/project.ts
  src/utils/const/client.ts
Labels: size/S

#112 Feat/#111 banner
  next.config.js
  src/components/Header/header.module.scss
  src/components/Header/menuTapList.ts
  src/lib/api/mock/about.ts
  src/lib/types/about.ts
  src/pages/about.tsx
  src/views/AboutPage/AboutPage.tsx
  src/views/AboutPage/components/Banner/index.tsx
  src/views/AboutPage/components/Banner/style.ts
  src/views/AboutPage/components/index.ts
  src/views/AboutPage/hooks/useFetch.ts
  src/views/AboutPage/index.ts
Labels: size/L
