Repository sopt-makers/sopt.org-frontend, pull requests merged in 2023-03, with the labels that each got.

#75 lint 워닝 제거
  src/components/common/CommonError/CommonError.tsx
  src/components/common/RoundButton/RoundButton.tsx
  src/utils/history.ts
Labels: size/S

#74 사용되지 않는 에셋 삭제
  src/assets/icons/SopkatonBackground.svg
  src/assets/icons/SopkatonReversedBackground.png
  src/assets/icons/SopkatonReversedBackground.svg
  src/assets/icons/apple_appstore.svg
  src/assets/icons/google_playstore.svg
  src/assets/icons/grientArrow.svg
  src/assets/icons/icArrowDown.svg
  src/assets/icons/instagram_icon.svg
  src/assets/icons/xButton.svg
  src/assets/icons/youtube_icon.svg
  src/assets/images/Appjam.svg
  src/assets/images/DotImg.svg
  src/assets/images/Networking.svg
  src/assets/images/SeminarImg.svg
  src/assets/images/Sopkathon.svg
  src/assets/images/Sopt-Term.svg
  src/assets/images/appjam_background.svg
  src/assets/images/bg-img.svg
  src/assets/images/rightArrow.svg
  src/assets/images/sopkaton1.png
  src/assets/images/sopkaton2.png
  src/assets/images/sopt_default_logo.png
  src/assets/images/sopt_default_logo.svg
  src/assets/images/sopterm1.png
  src/assets/images/sopterm2.png
  src/assets/images/sopterm_service.png
  src/assets/images/study_networking.png
  src/assets/images/study_networking.svg
  src/assets/images/team1.png
  src/assets/images/team2.png
  src/assets/images/youtube_logo.svg
  src/assets/logo/website.svg
Labels: size/L

#77 Feat/#76 header review tap
  src/components/Header/Desktop/DesktopHeader.tsx
  src/components/Header/Header.tsx
  src/components/Header/Mobile/HeaderMenu.tsx
  src/hooks/useHeader.ts
  src/pages/review.tsx
  src/views/ReviewPage/ReviewPage.tsx
  src/views/ReviewPage/index.tsx
Labels: enhancement, size/L

#79 Develop to Main
  src/assets/icons/SopkatonBackground.svg
  src/assets/icons/SopkatonReversedBackground.png
  src/assets/icons/SopkatonReversedBackground.svg
  src/assets/icons/apple_appstore.svg
  src/assets/icons/google_playstore.svg
  src/assets/icons/grientArrow.svg
  src/assets/icons/icArrowDown.svg
  src/assets/icons/instagram_icon.svg
  src/assets/icons/xButton.svg
  src/assets/icons/youtube_icon.svg
  src/assets/images/Appjam.svg
  src/assets/images/DotImg.svg
  src/assets/images/Networking.svg
  src/assets/images/SeminarImg.svg
  src/assets/images/Sopkathon.svg
  src/assets/images/Sopt-Term.svg
  src/assets/images/appjam_background.svg
  src/assets/images/bg-img.svg
  src/assets/images/rightArrow.svg
  src/assets/images/sopkaton1.png
  src/assets/images/sopkaton2.png
  src/assets/images/sopt_default_logo.png
  src/assets/images/sopt_default_logo.svg
  src/assets/images/sopterm1.png
  src/assets/images/sopterm2.png
  src/assets/images/sopterm_service.png
  src/assets/images/study_networking.png
  src/assets/images/study_networking.svg
  src/assets/images/team1.png
  src/assets/images/team2.png
  src/assets/images/youtube_logo.svg
  src/assets/logo/website.svg
  src/components/Header/Desktop/DesktopHeader.tsx
  src/components/Header/Header.tsx
  src/components/Header/Mobile/HeaderMenu.tsx
  src/components/common/CommonError/CommonError.tsx
  src/components/common/RoundButton/RoundButton.tsx
  src/hooks/useHeader.ts
  src/pages/review.tsx
  src/utils/history.ts
  src/views/ReviewPage/ReviewPage.tsx
  src/views/ReviewPage/index.tsx
Labels: size/L

#80 헤더 메뉴 탭 로직 수정
  src/components/Header/Desktop/DesktopHeader.tsx
  src/components/Header/Header.tsx
  src/components/Header/Mobile/HeaderMenu.style.ts
  src/components/Header/Mobile/HeaderMenu.tsx
  src/components/Header/Mobile/MobileHeader.tsx
  src/components/Header/menuTapList.ts
  src/components/Header/types.ts
  src/hooks/useHeader.ts
  src/hooks/useNoScroll.ts
Labels: enhancement, size/L

#81 클릭 가능한 엘리먼트에게 cursor: pointer 주기
  src/components/Footer/Channels/Channels.style.tsx
  src/components/Footer/Channels/Channels.tsx
  src/views/FAQPage/components/contact/ContactInfo.tsx
  src/views/FAQPage/components/faq/QuestionBox.tsx
  src/views/MainPage/components/ActivityDescription/activity-description.module.scss
  src/views/MainPage/components/DetailedInformation/detailed-information.module.scss
  src/views/MainPage/components/PartDescription/part-description.module.scss
Labels: size/M

#83 리뷰 페이지 UI 작업
  package.json
  pnpm-lock.yaml
  src/assets/mainLogo/index.ts
  src/assets/mainLogo/logo_11.svg
  src/assets/mainLogo/logo_12.svg
  src/assets/mainLogo/logo_14.svg
  src/assets/mainLogo/logo_15.svg
  src/assets/mainLogo/logo_16.svg
  src/assets/mainLogo/logo_17.svg
  src/assets/mainLogo/logo_18.svg
  src/assets/mainLogo/logo_19.svg
  src/assets/mainLogo/logo_20.svg
  src/assets/mainLogo/logo_21.svg
  src/assets/mainLogo/logo_22.svg
  src/assets/mainLogo/logo_23.svg
  src/assets/mainLogo/logo_24.svg
  src/assets/mainLogo/logo_25.svg
  src/assets/mainLogo/logo_26.svg
  src/assets/mainLogo/logo_27.svg
  src/assets/mainLogo/logo_28.svg
  src/assets/mainLogo/logo_29.svg
  src/assets/mainLogo/logo_30.svg
  src/assets/mainLogo/logo_31.svg
  src/components/Header/menuTapList.ts
  src/hooks/useFetchBase/index.ts
  src/hooks/useFetchBase/reducer.ts
  src/hooks/useFetchBase/types.ts
  src/lib/project.ts
  src/lib/review.ts
  src/views/ProjectPage/components/project/ProjectList.tsx
  src/views/ProjectPage/hooks/useFetch.ts
  src/views/ProjectPage/types.ts
  src/views/ReviewPage/ReviewPage.tsx
  src/views/ReviewPage/components/Description/index.tsx
  src/views/ReviewPage/components/Reviews/Loading/index.tsx
  src/views/ReviewPage/components/Reviews/Loading/style.ts
  src/views/ReviewPage/components/Reviews/index.tsx
  src/views/ReviewPage/components/Reviews/style.ts
  src/views/ReviewPage/components/TabBar/index.tsx
  src/views/ReviewPage/components/TabBar/style.ts
  src/views/ReviewPage/components/index.ts
  src/views/ReviewPage/hooks/useFetch.ts
  src/views/ReviewPage/libs/constants.ts
  src/views/ReviewPage/types/index.tsx
Labels: size/XL

#89 Feat/sp0 joohaem
  src/styles/_mixins.scss
  src/views/MainPage/components/ActivityReview/ActivityReview.tsx
  src/views/MainPage/components/ActivityReview/activity-review.module.scss
  src/views/MainPage/stylesheets/_mixins.scss
Labels: size/S

#91 메인 페이지의 에러 및 워닝 제거
  src/assets/sopt/main-page_banner-compression.png
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/views/MainPage/components/ActivityReview/ActivityReview.tsx
  src/views/MainPage/components/ActivityReview/activity-review.module.scss
  src/views/MainPage/components/BannerImage/BannerImage.tsx
Labels: size/M

#92 Feat/sp0 render optimizing
  package.json
  pnpm-lock.yaml
  public/fonts/SUIT-Bold.woff2
  public/fonts/SUIT-ExtraBold.woff2
  public/fonts/SUIT-ExtraLight.woff2
  public/fonts/SUIT-Heavy.woff2
  public/fonts/SUIT-Light.woff2
  public/fonts/SUIT-Medium.woff2
  public/fonts/SUIT-Regular.woff2
  public/fonts/SUIT-SemiBold.woff2
  public/fonts/SUIT-Thin.woff2
  src/assets/sopt/logo.png
  src/assets/sopt/logo.ts
  src/components/Footer/Footer.style.tsx
  src/components/Header/Desktop/DesktopHeader.tsx
  src/components/Header/Mobile/HeaderMenu.style.ts
  src/components/Header/Mobile/MobileHeader.tsx
  src/components/common/RoundButton/RoundButton.style.tsx
  src/components/common/ScrollToTopButton/ScrollToTopButton.tsx
  src/components/common/ScrollToTopButton/scroll-to-top-button.module.scss
  src/pages/404.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/recruit.tsx
  src/styles/font.css
  src/styles/font.ts
  src/styles/global.ts
  src/styles/globals.css
  src/views/FAQPage/components/contact/ContactInfo.tsx
  src/views/FAQPage/components/faq/QuestionBox.tsx
  src/views/FAQPage/components/faq/index.tsx
  src/views/MainPage/components/ActivityReview/activity-review.module.scss
  src/views/ProjectPage/components/common/empty.module.scss
  src/views/ProjectPage/components/filter/project-filter-desktop.module.scss
  src/views/ProjectPage/components/filter/project-filter-mobile.module.scss
  src/views/ProjectPage/components/project/project-card.module.scss
  src/views/ProjectPage/components/project/project-enroll.module.scss
  src/views/ProjectPage/components/project/project-list.module.scss
  src/views/RulesPage/CollapseLi/CollapseLi.style.tsx
  src/views/RulesPage/UnderlinedText/UnderlinedText.style.tsx
Labels: size/L

#93 sp0 활동 후기 무한 스크롤
  src/hooks/useBooleanState.ts
  src/hooks/useIntersectionObserver.ts
  src/hooks/useStackedFetchBase/index.ts
  src/hooks/useStackedFetchBase/reducer.ts
  src/hooks/useStackedFetchBase/types.ts
  src/lib/review.ts
  src/styles/textEllipsis.ts
  src/views/ProjectPage/hooks/useInfiniteScroll.ts
  src/views/ReviewPage/ReviewPage.tsx
  src/views/ReviewPage/components/Reviews/index.tsx
  src/views/ReviewPage/components/Reviews/style.ts
  src/views/ReviewPage/hooks/useFetch.ts
  src/views/ReviewPage/hooks/useInfiniteScroll.ts
Labels: size/L
