Repository sopt-makers/sopt.org-frontend, pull requests merged in 2023-12, with the labels that each got.

#304 프로젝트 탭의 사용해보기 버튼에 transition을 추가해요
  src/views/ProjectPage/components/RecentProjectList/Item/style.ts
Labels: size/XS

#306 [SP2]footer z-index 변경
  src/components/Footer/MakersNForm/style.ts
Labels: size/XS

#312 [SP2] 최근 릴리즈된 프로젝트 데이터 수정
  src/lib/constants/project.ts
Labels: size/S

#294 [SP2] 메인페이지 뒤집히는 카드 효과 만들기
  src/assets/images/img_main_makers_card.png
  src/assets/images/img_main_mind_card.png
  src/components/common/FlippableCard/index.tsx
  src/components/common/FlippableCard/style.ts
  src/lib/constants/main.ts
  src/lib/types/universal.ts
  src/views/MainPage/MainPage.tsx
  src/views/MainPage/components/OwnOrganization/Card/index.tsx
  src/views/MainPage/components/OwnOrganization/Card/style.ts
  src/views/MainPage/components/OwnOrganization/index.tsx
  src/views/MainPage/components/OwnOrganization/style.ts
Labels: size/L

#308 [SP2] 메인 페이지 하단 파트 섹션
  src/assets/icons/ic_arrow_left.svg
  src/assets/icons/ic_arrow_right.svg
  src/hooks/useInfiniteCarousel.ts
  src/lib/constants/main.ts
  src/lib/types/main.ts
  src/views/MainPage/MainPage.tsx
  src/views/MainPage/components/PartConfig/PartButton.tsx/index.tsx
  src/views/MainPage/components/PartConfig/PartButton.tsx/style.ts
  src/views/MainPage/components/PartConfig/PartSlide/index.tsx
  src/views/MainPage/components/PartConfig/PartSlide/style.ts
  src/views/MainPage/components/PartConfig/index.tsx
  src/views/MainPage/components/PartConfig/style.ts
  src/views/RecruitPage/components/ChapterInfo/index.tsx
Labels: size/XL

#317 [SP3] 메인 하단 파트 구성 섹션 반응형
  src/assets/icons/ic_arrow_left.svg
  src/assets/icons/ic_arrow_right.svg
  src/hooks/useDrag.ts
  src/hooks/useInfiniteCarousel.ts
  src/lib/constants/main.ts
  src/lib/types/main.ts
  src/views/MainPage/components/PartConfig/PartButton.tsx/style.ts
  src/views/MainPage/components/PartConfig/PartSlide/index.tsx
  src/views/MainPage/components/PartConfig/PartSlide/style.ts
  src/views/MainPage/components/PartConfig/index.tsx
  src/views/MainPage/components/PartConfig/style.ts
Labels: size/XL

#315 [SP3]액티비티 반응형 및 애니메이션
  package.json
  src/views/MainPage/components/Activity/Card/index.tsx
  src/views/MainPage/components/Activity/Card/style.ts
  src/views/MainPage/components/Activity/MobileCard/index.tsx
  src/views/MainPage/components/Activity/MobileCard/style.ts
  src/views/MainPage/components/Activity/index.tsx
Labels: size/L

#322 [SP3] 액티비티 내용 수정 및 useInfiniteCarousel 적용
  src/lib/constants/main.ts
  src/lib/types/main.ts
  src/views/MainPage/components/Activity/Card/style.ts
  src/views/MainPage/components/Activity/MobileCard/index.tsx
  src/views/MainPage/components/Activity/MobileCard/style.ts
  src/views/MainPage/components/Activity/index.tsx
  src/views/MainPage/components/Activity/style.ts
Labels: size/L

#324 [SP3] 메인 하단 레이아웃
  package.json
  src/assets/icons/ic_polygon.svg
  src/hooks/useInView.ts
  src/hooks/useIntersectionObserver.ts
  src/lib/constants/main.ts
  src/lib/types/main.ts
  src/pages/_app.tsx
  src/views/MainPage/MainPage.tsx
  src/views/MainPage/components/Activity/Card/style.ts
  src/views/MainPage/components/Activity/MobileCard/index.tsx
  src/views/MainPage/components/Activity/MobileCard/style.ts
  src/views/MainPage/components/Activity/index.tsx
  src/views/MainPage/components/Activity/style.ts
  src/views/MainPage/components/ActivitySection/index.tsx
  src/views/MainPage/components/ActivitySection/style.ts
  src/views/MainPage/components/BottomLayout/index.tsx
  src/views/MainPage/components/BottomLayout/style.ts
  src/views/MainPage/components/IntroSection/index.tsx
  src/views/MainPage/components/OwnOrganization/index.tsx
  src/views/MainPage/components/OwnOrganization/style.ts
  src/views/MainPage/components/PartConfig/index.tsx
  src/views/MainPage/components/PartConfig/style.ts
  src/views/MainPage/components/RecentNews/index.tsx
  src/views/MainPage/components/RecruitMessage/style.ts
Labels: size/XL

#325 [SP3] 메인페이지에 리뷰 부분 추가
  pnpm-lock.yaml
  src/lib/constants/main.ts
  src/lib/types/main.ts
  src/views/MainPage/components/BottomLayout/index.tsx
  src/views/MainPage/components/Comment/Card/Desktop/index.tsx
  src/views/MainPage/components/Comment/Card/Desktop/style.ts
  src/views/MainPage/components/Comment/Card/Mobile/index.tsx
  src/views/MainPage/components/Comment/Card/Mobile/style.ts
  src/views/MainPage/components/Comment/Cards/index.tsx
  src/views/MainPage/components/Comment/index.tsx
  src/views/MainPage/components/Comment/style.ts
Labels: size/XL

#330 [SP3] 모바일 메인 하단 백그라운드 제거
  src/views/MainPage/components/BottomLayout/style.ts
Labels: size/XS

#331 [SP3] 메인페이지 QA 작업
  src/assets/icons/ic_instagram.svg
  src/lib/constants/main.ts
  src/views/MainPage/components/Activity/index.tsx
  src/views/MainPage/components/Banner/RecruitButton/index.tsx
  src/views/MainPage/components/Banner/RecruitButton/style.ts
  src/views/MainPage/components/RecentNews/index.tsx
  src/views/MainPage/components/RecentNews/style.ts
  src/views/MainPage/components/RecruitMessage/style.ts
  src/views/MainPage/components/Tab/style.ts
Labels: size/L

#333 메인페이지 QA
  src/views/MainPage/components/Banner/style.ts
  src/views/MainPage/components/Introduce/index.tsx
Labels: size/XS

#332 [SP3] 메인 페이지 QA 작업
  src/assets/icons/ic_arrow_comment.svg
  src/assets/images/img_main_makers_card_mo.png
  src/assets/images/img_main_makers_card_pc.png
  src/assets/images/img_main_mind_card_mo.png
  src/assets/images/img_main_mind_card_pc.png
  src/components/common/FlippableCard/index.tsx
  src/lib/constants/main.ts
  src/views/MainPage/components/BottomLayout/index.tsx
  src/views/MainPage/components/BottomLayout/style.ts
  src/views/MainPage/components/Comment/Card/Desktop/index.tsx
  src/views/MainPage/components/Comment/Card/Desktop/style.ts
  src/views/MainPage/components/Comment/Cards/index.tsx
  src/views/MainPage/components/Comment/index.tsx
  src/views/MainPage/components/Comment/style.ts
  src/views/MainPage/components/OwnOrganization/Card/index.tsx
  src/views/MainPage/components/OwnOrganization/Card/style.ts
  src/views/MainPage/components/ScrollInteractiveLogo/index.tsx
  src/views/MainPage/components/ScrollInteractiveLogo/style.ts
Labels: size/L

#336 [SP3] 헤더 디자인 변경
  src/components/Header/Desktop/DesktopHeader.tsx
  src/components/Header/Header.tsx
  src/components/Header/Mobile/HeaderMenu.style.ts
  src/components/Header/Mobile/HeaderMenu.tsx
  src/components/Header/Mobile/MobileHeader.tsx
  src/components/Header/menuTapList.ts
  src/components/Header/style.ts
  src/components/Header/types.ts
Labels: size/L

#337 [SP3] 메인 QA 작업
  src/hooks/useInfiniteCarousel.ts
  src/lib/constants/main.ts
  src/views/MainPage/components/Activity/Card/style.ts
  src/views/MainPage/components/Activity/MobileCard/index.tsx
  src/views/MainPage/components/Activity/MobileCard/style.ts
  src/views/MainPage/components/ActivitySection/style.ts
  src/views/MainPage/components/BottomLayout/index.tsx
  src/views/MainPage/components/BottomLayout/style.ts
  src/views/MainPage/components/IntroSection/IntroContent/style.ts
  src/views/MainPage/components/PartConfig/PartButton.tsx/index.tsx
  src/views/MainPage/components/PartConfig/PartSlide/index.tsx
  src/views/MainPage/components/PartConfig/PartSlide/style.ts
  src/views/MainPage/components/PartConfig/index.tsx
  src/views/MainPage/components/PartConfig/style.ts
  src/views/MainPage/components/RecentNews/index.tsx
  src/views/MainPage/components/RecentNews/style.ts
Labels: size/L

#338 [SP3] 리크루팅 메시지 마진 조정
  src/views/MainPage/components/RecruitMessage/style.ts
Labels: size/XS

#340 [SP3] 중복 화살표 제거
  src/views/MainPage/components/Activity/MobileCard/index.tsx
Labels: size/XS

#341 [SP3] 자치기구 반응형, 활동후기 글자 부활, 솝트어때요와 최신소식 사이 간격 늘리기
  src/views/MainPage/components/Comment/Card/Desktop/index.tsx
  src/views/MainPage/components/Comment/index.tsx
  src/views/MainPage/components/Comment/style.ts
  src/views/MainPage/components/OwnOrganization/Card/style.ts
  src/views/MainPage/components/OwnOrganization/style.ts
Labels: size/M

#343 [SP3]헤더 탭 타이틀명 변경
  src/components/Header/menuTapList.ts
Labels: size/XS

#344 [SP3] 자치기구의 makers의 s가 잘리지 않도록 변경
  src/views/MainPage/components/OwnOrganization/Card/style.ts
  src/views/MainPage/components/OwnOrganization/style.ts
Labels: size/S

#345 [SP3] 솝트어때요? 반응형 최최최종 수정
  src/views/MainPage/components/Comment/Card/Desktop/index.tsx
  src/views/MainPage/components/Comment/Card/Desktop/style.ts
  src/views/MainPage/components/Comment/Cards/index.tsx
  src/views/MainPage/components/Comment/style.ts
Labels: size/M

#346 [SP3] 솝트어때요? isInView 훅의 마진 진짜 고침
  src/views/MainPage/components/Comment/Card/Desktop/index.tsx
Labels: size/XS
