Repository sopt-makers/sopt.org-frontend, pull requests merged in 2023-05, with the labels that each got.

#114 chore: split about api and members api
  src/lib/api/mock/about.ts
  src/lib/types/about.ts
Labels: size/S

#113 feat: About 페이지의 핵심 가치 섹션 구현
  src/components/common/Flex/index.tsx
  src/lib/api/mock/about.ts
  src/views/AboutPage/AboutPage.tsx
  src/views/AboutPage/components/CoreValue/Item/index.tsx
  src/views/AboutPage/components/CoreValue/Item/style.ts
  src/views/AboutPage/components/CoreValue/List/index.tsx
  src/views/AboutPage/components/CoreValue/Section/index.tsx
  src/views/AboutPage/components/CoreValue/Section/style.ts
  src/views/AboutPage/components/common/SectionDescription/index.tsx
  src/views/AboutPage/components/common/SectionTitle/index.tsx
Labels: size/L

#115 feat: About 탭 커리큘럼 섹션 구현
  next.config.js
  src/lib/api/mock/about.ts
  src/lib/api/remote/review.ts
  src/lib/types/about.ts
  src/lib/types/review.ts
  src/lib/types/universal.ts
  src/views/AboutPage/AboutPage.tsx
  src/views/AboutPage/components/Cirriculum/Content/index.tsx
  src/views/AboutPage/components/Cirriculum/Content/style.ts
  src/views/AboutPage/components/Cirriculum/Section/index.tsx
  src/views/AboutPage/components/common/TabBar/index.tsx
  src/views/AboutPage/components/common/TabBar/style.ts
  src/views/AboutPage/constant/taps.ts
  src/views/AboutPage/hooks/useFetch.ts
  src/views/MainPage/lib/useTabs.ts
  src/views/ReviewPage/ReviewPage.tsx
  src/views/ReviewPage/components/Reviews/index.tsx
  src/views/ReviewPage/components/TabBar/index.tsx
  src/views/ReviewPage/hooks/useFetch.ts
  src/views/ReviewPage/libs/constants.ts
Labels: size/L

#116 #111 about 탭 멤버 섹션 구현
  src/views/AboutPage/AboutPage.tsx
  src/views/AboutPage/components/Member/Card/index.tsx
  src/views/AboutPage/components/Member/Card/style.ts
  src/views/AboutPage/components/Member/Content/index.tsx
  src/views/AboutPage/components/Member/Content/style.ts
  src/views/AboutPage/components/Member/Section/index.tsx
  src/views/AboutPage/hooks/useFetchMemeber.ts
  src/views/ProjectPage/components/filter/DesktopFilter.tsx
  src/views/ProjectPage/components/filter/MobileFilter.tsx
  src/views/ProjectPage/components/filter/MobileFilterModal.tsx
  src/views/ProjectPage/components/filter/ProjectFilter.tsx
Labels: size/L

#118 feat: implement about pages' study api
  src/lib/api/mock/about.ts
  src/lib/types/about.ts
  src/pages/study.tsx
  src/utils/dateFormat.ts
  src/views/AboutPage/AboutPage.tsx
  src/views/AboutPage/components/Record/Item/index.tsx
  src/views/AboutPage/components/Record/Item/style.ts
  src/views/AboutPage/components/Record/List/index.tsx
  src/views/AboutPage/components/Record/Section/index.tsx
  src/views/StudyPage/StudyPage.tsx
  src/views/StudyPage/components/Item/index.tsx
  src/views/StudyPage/components/Item/style.ts
  src/views/StudyPage/components/List/index.tsx
  src/views/StudyPage/components/List/style.ts
  src/views/StudyPage/components/Section/index.tsx
  src/views/StudyPage/components/Section/style.ts
  src/views/StudyPage/hooks/useFetch.ts
  src/views/StudyPage/index.tsx
Labels: size/XL

#119 Feat/#111 api layer
  next.config.js
  src/lib/api/index.ts
  src/lib/api/remote/about.ts
  src/lib/types/about.ts
  src/lib/types/dto.ts
  src/utils/parseStringToPart.ts
  src/views/AboutPage/AboutPage.tsx
  src/views/AboutPage/components/Banner/index.tsx
  src/views/AboutPage/components/Member/Card/index.tsx
  src/views/AboutPage/components/Member/Content/index.tsx
  src/views/AboutPage/components/Member/Content/style.ts
Labels: size/L

#121 chore: set Environment Variable
  src/utils/const/client.ts
Labels: size/XS

#123 SPR1 QA (스터디 페이지 / 활동 멤버 / 푸터)
  src/components/Footer/Channels/index.tsx
  src/components/Footer/OriginFooter/index.tsx
  src/components/Footer/OriginFooter/style.ts
  src/lib/api/remote/about.ts
  src/lib/types/about.ts
  src/utils/dateFormat.ts
  src/views/AboutPage/components/Member/Card/index.tsx
  src/views/AboutPage/components/Member/Card/style.ts
  src/views/AboutPage/components/Member/Content/index.tsx
  src/views/AboutPage/components/Record/List/index.tsx
  src/views/AboutPage/components/common/TabBar/style.ts
  src/views/StudyPage/components/Item/index.tsx
  src/views/StudyPage/components/Item/style.ts
Labels: size/L

#124 SPR1 QA (활동 멤버)
  src/assets/images/null_image.png
  src/views/AboutPage/components/Member/Card/index.tsx
  src/views/AboutPage/components/Member/Card/style.ts
Labels: size/XS

#127 SPR1 QA (인터렉션 / 핵심가치 / 레코드)
  src/components/Header/Mobile/HeaderMenu.style.ts
  src/components/common/NumberRoller/index.tsx
  src/hooks/useInView.ts
  src/lib/styles/animation.ts
  src/utils/platform.ts
  src/views/AboutPage/components/CoreValue/Item/index.tsx
  src/views/AboutPage/components/CoreValue/Item/style.ts
  src/views/AboutPage/components/CoreValue/List/index.tsx
  src/views/AboutPage/components/Member/Section/index.tsx
  src/views/AboutPage/components/Record/Item/index.tsx
  src/views/AboutPage/components/Record/Item/style.ts
  src/views/AboutPage/components/Record/List/index.tsx
  src/views/AboutPage/components/common/SectionDescription/index.tsx
Labels: size/L

#126 About 탭 데이터 Server Side 데이터 패칭
  src/pages/about.tsx
  src/views/AboutPage/AboutPage.tsx
  src/views/AboutPage/index.ts
Labels: size/L

#133 활동후기 패칭 ISSUE 해결
  src/components/common/ScrollToTopButton/ScrollToTopButton.tsx
  src/hooks/useStackedFetchBase/index.ts
  src/hooks/useStackedFetchBase/reducer.ts
  src/utils/debounce.ts
  src/utils/scrollDebounce.ts
  src/views/ReviewPage/ReviewPage.tsx
  src/views/ReviewPage/components/Content/index.tsx
  src/views/ReviewPage/components/Reviews/index.tsx
  src/views/ReviewPage/hooks/useFetch.ts
Labels: size/L
