Repository sopt-makers/sopt.org-frontend, pull requests merged in 2023-10, with the labels that each got.

#184 [SP1] 일부 컴포넌트에 dynamic import, lazy loading 적용
  src/components/Footer/Footer.tsx
  src/components/Footer/index.ts
  src/components/Footer/index.tsx
  src/components/common/DummyDiv/index.tsx
  src/components/common/PageLayout/index.tsx
  src/components/common/ScrollToTopButton/index.ts
  src/components/common/ScrollToTopButton/index.tsx
  src/views/FAQPage/FAQPage.tsx
  src/views/MainPage/MainPage.tsx
  src/views/ProjectDetailPage/ProjectDetailPage.tsx
  src/views/ProjectPage/ProjectPage.tsx
  src/views/RecruitPage/RecruitPage.tsx
  src/views/RecruitPage/components/ActivityReview/index.tsx
  src/views/ReviewPage/ReviewPage.tsx
  src/views/RulesPage/Rules.tsx
  src/views/SopticlePage/SopticlePage.tsx
  src/views/SponsorPage/index.tsx
  src/views/StudyPage/StudyPage.tsx
Labels: size/L

#211 [SP2] 빌드 오류 수정
  src/pages/about.tsx
Labels: size/XS

#213 [SP2] CI 스크립트에 빌드 step 추가
  .github/workflows/ci.yml
Labels: size/XS

#209 feat : head 태그 컴포넌트로 분리 및 프로젝트별 og tag 적용
  src/components/common/HTMLHead/index.tsx
  src/pages/_app.tsx
  src/views/ProjectDetailPage/ProjectDetailPage.tsx
Labels: size/L

#207 [SP2] 리크루팅 알림신청 API를 inhouse API로 교체
  package.json
  pnpm-lock.yaml
  src/lib/constants/googlesheet-env.ts
  src/pages/api/register.ts
  src/views/RecruitPage/components/NotificationSection/index.tsx
Labels: size/L

#215 [SP1] 리쿠르팅 알림 신청 입력란에 이메일 pattern 추가
  src/views/RecruitPage/components/NotificationSection/index.tsx
Labels: size/XS

#222 [SP1] styles, utils 폴더 통합 및 mds 컬러 코드 추가
  src/components/Footer/OriginFooter/style.ts
  src/components/Header/Mobile/HeaderMenu.style.ts
  src/components/Header/header.module.scss
  src/components/common/RoundButton/RoundButton.style.tsx
  src/components/common/ScrollToTopButton/index.tsx
  src/components/common/ScrollToTopButton/scroll-to-top-button.module.scss
  src/components/common/Timer/Timer.tsx
  src/components/corporate/JobPostingCard/style.ts
  src/hooks/useStackedFetchBase/index.ts
  src/hooks/useStorage.ts
  src/lib/api/remote/about.ts
  src/lib/api/remote/sopticle.ts
  src/lib/styles/_mixins.scss
  src/lib/styles/_variables.scss
  src/lib/styles/colors.ts
  src/lib/styles/font.ts
  src/lib/styles/global.ts
  src/lib/styles/textEllipsis.ts
  src/lib/utils/convertMsIntoDate.ts
  src/lib/utils/dateFormat.ts
  src/lib/utils/debounce.ts
  src/lib/utils/pageViewTrackingEnrichment.ts
  src/lib/utils/parseStringToPart.ts
  src/lib/utils/platform.ts
  src/lib/utils/sanitize.ts
  src/lib/utils/storageHandler.ts
  src/pages/404.tsx
  src/pages/_app.tsx
  src/styles/colors.ts
  src/styles/emotion.d.ts
  src/styles/theme.ts
  src/views/AboutPage/components/Member/Card/style.ts
  src/views/ProjectDetailPage/ProjectDetailPage.tsx
  src/views/ProjectPage/components/common/empty.module.scss
  src/views/ProjectPage/components/filter/mobile-utility-button.module.scss
  src/views/ProjectPage/components/filter/project-filter-desktop.module.scss
  src/views/ProjectPage/components/filter/project-filter-mobile.module.scss
  src/views/ProjectPage/components/project/project-card.module.scss
  src/views/ProjectPage/components/project/project-enroll.module.scss
  src/views/ProjectPage/components/project/project-list.module.scss
  src/views/ReviewPage/components/Description/index.tsx
  src/views/ReviewPage/components/Reviews/style.ts
  src/views/RulesPage/components/CollapseLi/CollapseLi.style.tsx
  src/views/SopticlePage/components/Description/index.tsx
  src/views/SopticlePage/components/Sopticles/Card/index.tsx
  src/views/SopticlePage/components/Sopticles/style.ts
  src/views/StudyPage/components/Item/index.tsx
Labels: size/L

#231 [SP2] @sopt-makers/colors 적용
  package.json
  pnpm-lock.yaml
  src/components/Footer/OriginFooter/style.ts
  src/components/Header/Mobile/HeaderMenu.style.ts
  src/components/common/RoundButton/RoundButton.style.tsx
  src/lib/styles/colors.ts
  src/pages/404.tsx
  src/views/ReviewPage/components/Description/index.tsx
  src/views/RulesPage/components/CollapseLi/CollapseLi.style.tsx
  src/views/SopticlePage/components/Description/index.tsx
Labels: size/L

#228 [SP2] blog tab navigation
  src/components/Footer/OriginFooter/style.ts
  src/components/Header/Desktop/DesktopHeader.tsx
  src/components/Header/Header.tsx
  src/components/Header/Mobile/HeaderMenu.style.ts
  src/components/Header/Mobile/HeaderMenu.tsx
  src/components/Header/header.module.scss
  src/components/Header/menuTapList.ts
  src/components/Header/style.ts
  src/components/Header/types.ts
  src/lib/styles/colors.ts
  src/lib/styles/global.ts
  src/pages/blog.tsx
  src/views/BlogPage/BlogPage.tsx
  src/views/BlogPage/components/blogTab/index.tsx
  src/views/BlogPage/components/blogTab/style.ts
  src/views/BlogPage/components/blogTab/types.ts
  src/views/BlogPage/index.tsx
Labels: size/XL

#232 [SP2] 블로그 탭 게시물 목록 구현
  src/assets/icons/ic_heart_filled.svg
  src/assets/icons/ic_heart_unfilled.svg
  src/assets/icons/ic_profile_default.svg
  src/lib/styles/colors.ts
  src/lib/types/blog.ts
  src/views/BlogPage/components/BlogPost/DefaultProfileImage/index.tsx
  src/views/BlogPage/components/BlogPost/DefaultProfileImage/style.ts
  src/views/BlogPage/components/BlogPost/Header/index.tsx
  src/views/BlogPage/components/BlogPost/Header/style.ts
  src/views/BlogPage/components/BlogPost/Like/index.tsx
  src/views/BlogPage/components/BlogPost/Like/style.ts
  src/views/BlogPage/components/BlogPost/index.tsx
  src/views/BlogPage/components/BlogPost/style.ts
  src/views/BlogPage/components/BlogPostList/index.tsx
  src/views/BlogPage/components/BlogPostList/style.ts
Labels: size/XL

#223 [SP2] 드롭다운 컴포넌트 추가, 프로젝트 페이지 필터에 적용
  src/components/common/Select/index.tsx
  src/components/common/Select/style.ts
  src/hooks/useOutsideClickListener.ts
  src/lib/constants/gtmClass.ts
  src/lib/constants/project.ts
  src/lib/types/universal.ts
  src/views/ProjectPage/ProjectPage.tsx
  src/views/ProjectPage/components/filter/DesktopFilter.tsx
  src/views/ProjectPage/components/filter/MobileFilter.tsx
  src/views/ProjectPage/components/filter/MobileFilterModal.tsx
  src/views/ProjectPage/components/filter/MobileUtilityButton.tsx
  src/views/ProjectPage/components/filter/ProjectFilter.tsx
  src/views/ProjectPage/components/filter/mobile-utility-button.module.scss
  src/views/ProjectPage/components/filter/project-filter-desktop.module.scss
  src/views/ProjectPage/components/filter/project-filter-mobile.module.scss
  src/views/ProjectPage/components/index.ts
  src/views/ProjectPage/components/project/ProjectList.tsx
  src/views/ProjectPage/components/project/project-list.module.scss
  src/views/ProjectPage/styles.ts
Labels: size/XL

#227 [SP2] 솝티클 중 네이버 블로그 썸네일이 깨지는 현상 해결
  next.config.js
Labels: size/XS

#239 [SP2] 네비게이션 클릭 범위 수정
  src/components/Header/Desktop/DesktopHeader.tsx
  src/components/common/Select/style.ts
  src/views/ProjectPage/styles.ts
Labels: size/S

#241 [SP2] 후원 탭 채용 공고 데이터 추가
  src/assets/corperates/codeit.png
  src/assets/corperates/doodlin.png
  src/assets/corperates/greenlabs.png
  src/assets/corperates/index.ts
  src/assets/corperates/levit.webp
  src/assets/corperates/miridih.png
  src/assets/corperates/ringle.png
  src/assets/corperates/teamSparta.png
  src/assets/corperates/toss.jpeg
  src/assets/corperates/voyagerx.png
  src/lib/api/mock/job.ts
Labels: size/L

#237 [SP2] 프로젝트 탭 레이아웃 스타일 반영
  src/components/common/Select/style.ts
  src/lib/constants/project.ts
  src/views/ProjectPage/ProjectPage.tsx
  src/views/ProjectPage/components/RecentProjectList/index.tsx
  src/views/ProjectPage/components/project/ProjectList.tsx
  src/views/ProjectPage/components/project/project-list.module.scss
  src/views/ProjectPage/styles.ts
Labels: size/L

#243 [SP2] 프로젝트 탭에 플랫폼 필터 추가
  src/lib/api/remote/project.ts
  src/lib/constants/project.ts
  src/lib/types/project.ts
  src/views/ProjectPage/ProjectPage.tsx
  src/views/ProjectPage/components/RecentProjectList/index.tsx
  src/views/ProjectPage/hooks/useFetch.ts
  src/views/ProjectPage/styles.ts
Labels: size/L

#245 [SP2] 프로젝트 탭 피드 디자인 변경
  src/components/Layout/Layout.tsx
  src/lib/api/remote/project.ts
  src/lib/constants/project.ts
  src/lib/types/project.ts
  src/pages/project/[id]/index.tsx
  src/views/ProjectPage/ProjectPage.tsx
  src/views/ProjectPage/components/index.ts
  src/views/ProjectPage/components/project/ProjectCard.tsx
  src/views/ProjectPage/components/project/ProjectCard/index.tsx
  src/views/ProjectPage/components/project/ProjectCard/style.ts
  src/views/ProjectPage/components/project/ProjectCardList/index.tsx
  src/views/ProjectPage/components/project/ProjectCardList/style.ts
  src/views/ProjectPage/components/project/ProjectCategoryDescription/index.tsx
  src/views/ProjectPage/components/project/ProjectCategoryDescription/style.ts
  src/views/ProjectPage/components/project/ProjectEnrollSection.tsx
  src/views/ProjectPage/components/project/ProjectList.tsx
  src/views/ProjectPage/components/project/ProjectListCount/index.tsx
  src/views/ProjectPage/components/project/ProjectListCount/style.ts
  src/views/ProjectPage/components/project/index.ts
  src/views/ProjectPage/components/project/project-card.module.scss
  src/views/ProjectPage/components/project/project-enroll.module.scss
  src/views/ProjectPage/components/project/style.ts
Labels: size/XL

#248 [SP2] 프로젝트 탭 디테일한 디자인 수정
  src/components/common/Select/style.ts
  src/views/ProjectPage/ProjectPage.tsx
  src/views/ProjectPage/components/RecentProjectList/Carousel/index.tsx
  src/views/ProjectPage/components/RecentProjectList/Item/style.ts
  src/views/ProjectPage/components/project/ProjectCard/index.tsx
  src/views/ProjectPage/components/project/ProjectCardList/index.tsx
  src/views/ProjectPage/components/project/ProjectCardList/style.ts
  src/views/ProjectPage/components/project/ProjectCardSkeletonUI/index.tsx
  src/views/ProjectPage/components/project/ProjectCardSkeletonUI/style.ts
  src/views/ProjectPage/components/project/ProjectList.tsx
  src/views/ProjectPage/components/project/project-list.module.scss
  src/views/ProjectPage/components/project/style.ts
  src/views/ProjectPage/styles.ts
Labels: size/L
