Repository sopt-makers/sopt.org-frontend, pull requests merged in 2023-06, with the labels that each got.

#139 SPR 2 후원 공고 섹션 개설
  src/components/Footer/OriginFooter/style.ts
  src/components/corporate/JobPostingCard/index.tsx
  src/components/corporate/JobPostingCard/style.ts
  src/lib/api/index.ts
  src/lib/api/mock/job.ts
  src/lib/types/job.ts
  src/lib/types/universal.ts
  src/styles/global.ts
  src/styles/textEllipsis.ts
  src/views/AboutPage/components/Member/Card/style.ts
  src/views/AboutPage/components/common/TabBar/style.ts
  src/views/FAQPage/components/contact/ContactInfo.tsx
  src/views/FAQPage/components/contact/index.tsx
  src/views/FAQPage/components/faq/QuestionBox.tsx
  src/views/FAQPage/components/faq/index.tsx
  src/views/MainPage/MainPage.tsx
  src/views/MainPage/components/CorporateJob/FieldTabs/index.tsx
  src/views/MainPage/components/CorporateJob/FieldTabs/style.ts
  src/views/MainPage/components/CorporateJob/JobPostings/index.tsx
  src/views/MainPage/components/CorporateJob/JobPostings/style.ts
  src/views/MainPage/components/CorporateJob/index.tsx
  src/views/MainPage/components/CorporateJob/style.ts
  src/views/MainPage/lib/useTabs.ts
Labels: size/XL

#141 SPR 2 에러 처리 UI 구성
  src/components/DataErrorBanner/CautionIcon.tsx
  src/components/DataErrorBanner/index.tsx
  src/components/DataErrorBanner/style.ts
  src/hooks/useFetchBase/reducer.ts
  src/views/AboutPage/components/Member/Content/index.tsx
  src/views/AboutPage/constant/emptyMembers.ts
  src/views/AboutPage/hooks/useResponsiveMember.ts
Labels: size/L

#145 SPR 2 후원탭 신설 및 페이지 구성
  src/components/Header/menuTapList.ts
  src/hooks/useTabs.ts
  src/pages/sponsor.tsx
  src/views/MainPage/MainPage.tsx
  src/views/MainPage/components/ActivityDescription/ActivityDescription.tsx
  src/views/MainPage/components/ActivityReview/activity-review.module.scss
  src/views/MainPage/components/PartDescription/PartDescription.tsx
  src/views/MainPage/components/index.ts
  src/views/MainPage/lib/index.ts
  src/views/SponsorPage/components/CorporateJob/FieldTabs/index.tsx
  src/views/SponsorPage/components/CorporateJob/FieldTabs/style.ts
  src/views/SponsorPage/components/CorporateJob/JobPostings/index.tsx
  src/views/SponsorPage/components/CorporateJob/JobPostings/style.ts
  src/views/SponsorPage/components/CorporateJob/index.tsx
  src/views/SponsorPage/components/CorporateJob/style.ts
  src/views/SponsorPage/components/CorporateLinkedActivities/constants.ts
  src/views/SponsorPage/components/CorporateLinkedActivities/corporate-linked-activities.module.scss
  src/views/SponsorPage/components/CorporateLinkedActivities/index.tsx
  src/views/SponsorPage/components/CorporatePartner/constants.ts
  src/views/SponsorPage/components/CorporatePartner/corporate-partner.module.scss
  src/views/SponsorPage/components/CorporatePartner/index.tsx
  src/views/SponsorPage/components/index.ts
  src/views/SponsorPage/index.tsx
Labels: size/L

#147 SPR2 채용공고 (레브잇 올웨이즈)
  src/assets/corperates/levit.webp
  src/lib/api/mock/job.ts
  src/lib/types/job.ts
  src/views/SponsorPage/components/CorporateJob/JobPostings/index.tsx
Labels: size/M

#146 솝티클 릴리즈 QA
  next.config.js
  src/components/Header/Desktop/DesktopHeader.tsx
  src/components/Header/Mobile/HeaderMenu.style.ts
  src/components/Header/menuTapList.ts
  src/lib/api/remote/sopticle.ts
  src/lib/styles/animation.ts
  src/utils/sanitize.ts
  src/views/ReviewPage/components/TabBar/style.ts
  src/views/SopticlePage/components/TabBar/style.ts
Labels: size/L

#148 SPR2 QA : hover 상태 추가
  .babelrc
  package.json
  pnpm-lock.yaml
  src/components/Header/Desktop/DesktopHeader.tsx
  src/components/corporate/JobPostingCard/style.ts
  src/views/SopticlePage/components/Sopticles/style.ts
Labels: size/S

#150 hotfix: error banner 렌더링 조건
  src/views/AboutPage/components/Member/Content/index.tsx
Labels: size/XS

#151 hotfix: error banner 렌더링 조건
  src/views/AboutPage/components/Member/Content/index.tsx
Labels: size/XS
