Repository sopt-makers/sopt.org-frontend, pull requests merged in 2024-03, with the labels that each got.

#360 [SP0] OG 이미지 업데이트
  src/components/common/SEO/index.tsx
Labels: size/XS

#361 [SP-] 배포 시 일부 페이지가 amplitude 오류로 렌더되지 않는 오류 수정
  src/pages/_app.tsx
Labels: size/S

#362 [SP0] 34기 리크루팅 관련 메인페이지 업데이트
  .vscode/settings.json
  pnpm-lock.yaml
  src/assets/icons/ic_timer.svg
  src/assets/icons/ic_view.svg
  src/views/MainPage/MainPage.tsx
  src/views/MainPage/components/Banner/RecruitButton/style.ts
  src/views/MainPage/components/Banner/index.tsx
  src/views/MainPage/components/PartConfig/index.tsx
  src/views/MainPage/components/TopBanner/index.tsx
  src/views/MainPage/components/TopBanner/style.ts
  src/views/MainPage/hooks/useCheckTime.ts
  src/views/MainPage/hooks/useFetch.ts
  src/views/MainPage/hooks/usePost.ts
Labels: size/XXL

#364 [S0] 34기 리쿠르팅 관련 리크루팅 페이지 업데이트
  src/assets/icons/value_challenge.svg
  src/assets/icons/value_link.svg
  src/assets/icons/value_share.svg
  src/assets/images/img_recruit_bg.png
  src/assets/mainLogo/index.ts
  src/assets/mainLogo/logo_nowsopt.png
  src/assets/mainLogo/logo_sopt_nowsopt.svg
  src/hooks/useCheckTime.ts
  src/views/FAQPage/components/faq/QuestionBox.tsx
  src/views/MainPage/MainPage.tsx
  src/views/MainPage/hooks/usePost.ts
  src/views/RecruitPage/RecruitPage.tsx
  src/views/RecruitPage/components/ActivityReview/styles.ts
  src/views/RecruitPage/components/ApplySection/index.tsx
  src/views/RecruitPage/components/ApplySection/style.ts
  src/views/RecruitPage/components/BottomLogo/index.tsx
  src/views/RecruitPage/components/ChapterInfo/constants.ts
  src/views/RecruitPage/components/ChapterInfo/index.tsx
  src/views/RecruitPage/components/RecruteeInfo/index.tsx
  src/views/RecruitPage/components/RecruteeInfo/style.ts
  src/views/RecruitPage/components/Schedule/index.tsx
  src/views/RecruitPage/components/common/Tabs/style.ts
  src/views/RecruitPage/components/common/styles.ts
Labels: size/XL

#363 [SP0] 34기 리크루팅 관련 소개 페이지 업데이트
  public/images/members/1.png
  public/images/members/10.png
  public/images/members/11.png
  public/images/members/2.png
  public/images/members/3.png
  public/images/members/4.png
  public/images/members/5.png
  public/images/members/6.png
  public/images/members/7.png
  public/images/members/8.png
  public/images/members/9.png
  src/assets/mainLogo/img_logo_sopt.png
  src/assets/mainLogo/index.ts
  src/components/Footer/OriginFooter/style.ts
  src/components/Header/Desktop/DesktopHeader.tsx
  src/components/Header/Mobile/MobileHeader.tsx
  src/lib/api/mock/about.ts
  src/lib/api/remote/about.ts
  src/lib/types/about.ts
  src/views/AboutPage/components/CoreValue/Item/style.ts
  src/views/AboutPage/components/Curriculum/Content/style.ts
  src/views/AboutPage/components/Member/Card/style.ts
  src/views/AboutPage/components/Member/Section/index.tsx
  src/views/AboutPage/components/Record/Item/style.ts
  src/views/AboutPage/components/common/SectionTop/index.tsx
  src/views/AboutPage/components/common/SectionTop/style.ts
  src/views/AboutPage/components/common/TabBar/style.ts
Labels: size/L

#367 [S0] ios timestamp 오류 해결
  src/hooks/useCheckTime.ts
  src/views/MainPage/components/TopBanner/index.tsx
Labels: size/XS

#368 [SP0] 상용 배포 전 QA
  src/hooks/useCheckTime.ts
  src/lib/api/mock/about.ts
  src/views/MainPage/components/TopBanner/style.ts
  src/views/RecruitPage/components/ActivityReview/styles.ts
  src/views/RecruitPage/components/Contact/index.tsx
Labels: size/M

#371 [S0] 배포 후 QA
  src/views/AboutPage/components/CoreValue/Item/style.ts
  src/views/MainPage/components/Banner/RecruitButton/style.ts
  src/views/MainPage/components/RecruitMessage/index.tsx
  src/views/MainPage/components/TopBanner/style.ts
  src/views/RecruitPage/components/ChapterInfo/index.tsx
  src/views/RecruitPage/components/ChapterInfo/style.ts
  src/views/RecruitPage/components/Schedule/index.tsx
  src/views/RecruitPage/components/Schedule/style.ts
  src/views/RecruitPage/components/common/Tabs/style.ts
Labels: size/XL

#373 [S0] PM QA 반영
  src/lib/api/mock/about.ts
  src/views/RecruitPage/components/ApplySection/index.tsx
  src/views/RecruitPage/components/FAQ/constant.ts
Labels: size/M

#375 [SP0] 모집 마감 뷰 반영
  .vscode/settings.json
  src/hooks/useCheckTime.ts
  src/views/MainPage/MainPage.tsx
  src/views/MainPage/components/Banner/index.tsx
  src/views/MainPage/hooks/useCheckTime.ts
  src/views/RecruitPage/RecruitPage.tsx
Labels: size/M

#378 [SP0] 404, 500 에러페이지 제작
  src/components/common/RoundButton/RoundButton.tsx
  src/components/common/RoundButton/style.ts
  src/pages/404.tsx
  src/pages/500.tsx
  src/views/ErrorPage/ErrorPage.tsx
  src/views/ErrorPage/assets/ic_404_back.svg
  src/views/ErrorPage/assets/ic_404_front.svg
  src/views/ErrorPage/assets/ic_404_ghost.svg
  src/views/ErrorPage/assets/ic_404_ghost_dark.svg
  src/views/ErrorPage/assets/ic_500_back.svg
  src/views/ErrorPage/assets/ic_500_cone.svg
  src/views/ErrorPage/assets/ic_500_cone_dark.svg
  src/views/ErrorPage/assets/ic_500_front.svg
  src/views/ErrorPage/assets/index.ts
  src/views/ErrorPage/components/ErrorCode.style.ts
  src/views/ErrorPage/components/ErrorCode.tsx
  src/views/ErrorPage/constants/errorButton.ts
  src/views/ErrorPage/constants/errorMessage.ts
  src/views/ErrorPage/index.tsx
  src/views/ErrorPage/styles.ts
  src/views/MainPage/MainPage.tsx
Labels: size/L

#379 [SP0] 메인 페이지 수정사항 반영
  src/assets/icons/ic_instagram.svg
  src/assets/icons/ic_logo_sopt_white.svg
  src/assets/images/img_main_makers_card_big_pc.png
  src/assets/images/img_main_makers_card_mo.png
  src/assets/images/img_main_makers_card_pc.png
  src/assets/images/img_main_makers_card_ta.png
  src/assets/images/img_main_manage_card_big_pc.png
  src/assets/images/img_main_manage_card_mo.png
  src/assets/images/img_main_manage_card_pc.png
  src/assets/images/img_main_manage_card_ta.png
  src/assets/images/img_main_media_card_big_pc.png
  src/assets/images/img_main_media_card_mo.png
  src/assets/images/img_main_media_card_pc.png
  src/assets/images/img_main_media_card_ta.png
  src/assets/images/img_main_mind_card_big_pc.png
  src/assets/images/img_main_mind_card_mo.png
  src/assets/images/img_main_mind_card_pc.png
  src/assets/images/img_main_mind_card_ta.png
  src/lib/constants/main.ts
  src/views/MainPage/components/Activity/index.tsx
  src/views/MainPage/components/ActivitySection/index.tsx
  src/views/MainPage/components/ActivitySection/style.ts
  src/views/MainPage/components/Banner/RecruitButton/style.ts
  src/views/MainPage/components/Banner/index.tsx
  src/views/MainPage/components/Banner/style.ts
  src/views/MainPage/components/BottomLayout/index.tsx
  src/views/MainPage/components/BottomLayout/style.ts
  src/views/MainPage/components/Comment/Card/Desktop/index.tsx
  src/views/MainPage/components/Comment/Card/Mobile/style.ts
  src/views/MainPage/components/Comment/index.tsx
  src/views/MainPage/components/Comment/style.ts
  src/views/MainPage/components/Introduce/index.tsx
  src/views/MainPage/components/Introduce/style.ts
  src/views/MainPage/components/OwnOrganization/Card/index.tsx
  src/views/MainPage/components/OwnOrganization/Card/style.ts
  src/views/MainPage/components/OwnOrganization/index.tsx
  src/views/MainPage/components/OwnOrganization/style.ts
  src/views/MainPage/components/PartConfig/index.tsx
  src/views/MainPage/components/PartConfig/style.ts
  src/views/MainPage/components/RecentNews/Card/style.ts
  src/views/MainPage/components/RecentNews/index.tsx
  src/views/MainPage/components/RecentNews/style.ts
  src/views/MainPage/components/RecruitMessage/index.tsx
  src/views/MainPage/components/RecruitMessage/style.ts
  src/views/MainPage/components/ScrollInteractiveLogo/index.tsx
  src/views/MainPage/components/ScrollInteractiveLogo/style.ts
  src/views/MainPage/components/Tab/index.tsx
  src/views/MainPage/components/Tab/style.ts
  src/views/MainPage/components/TopBanner/index.tsx
Labels: size/XXL

#381 [SP0] 에러페이지 QA 반영
  src/components/Footer/MakersNForm/index.tsx
  src/components/common/RoundButton/style.ts
  src/views/ErrorPage/ErrorPage.tsx
  src/views/ErrorPage/components/ErrorCode.tsx
  src/views/ErrorPage/styles.ts
Labels: size/S

#385 [SP0] 메이커스 채널 1:1 채팅 연결
  src/components/Footer/MakersNForm/index.tsx
  src/components/Footer/MakersNForm/style.ts
  src/components/kakao/Script.tsx
  src/pages/_app.tsx
  src/views/ErrorPage/ErrorPage.tsx
  src/views/ErrorPage/styles.ts
Labels: size/M
