Repository sopt-makers/sopt.org-frontend, pull requests merged in 2024-09, with the labels that each got.

#407 [Feat] 35기 YB 리크루팅 페이지 업데이트
  pnpm-lock.yaml
  src/assets/images/img_recruit_banner.png
  src/assets/mainLogo/index.ts
  src/assets/mainLogo/logo_andsopt_dark.png
  src/components/Header/constants/menuTapList.ts
  src/hooks/useCheckTime.ts
  src/lib/utils/date.ts
  src/views/MainPage/components/Banner/index.tsx
  src/views/RecruitPage/components/ApplySection/index.tsx
  src/views/RecruitPage/components/ApplySection/style.ts
  src/views/RecruitPage/components/BottomLogo/index.tsx
  src/views/RecruitPage/components/ChapterInfo/constants.ts
  src/views/RecruitPage/components/ChapterInfo/style.ts
  src/views/RecruitPage/components/FAQ/QuestionBox/index.tsx
  src/views/RecruitPage/components/FAQ/constant.ts
  src/views/RecruitPage/components/Schedule/index.tsx
  src/views/RecruitPage/components/Schedule/style.ts
  src/views/RecruitPage/components/common/style.ts
  src/views/RecruitPage/index.tsx
Labels: size/XXL

#408 [Feat] 메인페이지 업데이트 + OG 이미지 변경
  src/components/common/SEO/index.tsx
  src/views/MainPage/components/Banner/RecruitButton/style.ts
  src/views/MainPage/components/Banner/index.tsx
  src/views/MainPage/components/TopBanner/index.tsx
  src/views/MainPage/components/TopBanner/style.ts
  src/views/MainPage/index.tsx
Labels: size/M

#410 [Feat] 소개페이지 업데이트
  public/images/members/1.png
  public/images/members/10.png
  public/images/members/11.png
  public/images/members/12.png
  public/images/members/2.png
  public/images/members/3.png
  public/images/members/4.png
  public/images/members/5.png
  public/images/members/6.png
  public/images/members/7.png
  public/images/members/8.png
  public/images/members/9.png
  src/lib/api/mock/about.ts
  src/lib/api/remote/about.ts
  src/views/AboutPage/components/CoreValue/Item/style.ts
  src/views/AboutPage/components/Member/Section/index.tsx
Labels: size/L

#413 [Chore] 오타 수정
  src/views/AboutPage/components/Record/Section/index.tsx
  src/views/RecruitPage/components/ChapterInfo/index.tsx
  src/views/RecruitPage/components/ChapterInfo/style.ts
Labels: size/S

#416 [Feat] memberInfo RQ에서 SSG fetching으로 수정
  src/pages/about.tsx
  src/views/AboutPage/components/Member/Content/index.tsx
  src/views/AboutPage/components/Member/Section/index.tsx
  src/views/AboutPage/components/Member/Section/style.ts
Labels: size/L

#418 [Revert] "[Feat] memberInfo RQ에서 SSG fetching으로 수정"
  src/pages/about.tsx
  src/views/AboutPage/components/Member/Content/index.tsx
  src/views/AboutPage/components/Member/Section/index.tsx
  src/views/AboutPage/components/Member/Section/style.ts
Labels: size/L

#419 [Refactor] memberInfo RQ에서 SSG fetching으로 수정
  src/pages/about.tsx
  src/views/AboutPage/components/Member/Card/index.tsx
  src/views/AboutPage/components/Member/Content/index.tsx
  src/views/AboutPage/components/Member/Content/style.ts
  src/views/AboutPage/components/Member/Section/index.tsx
  src/views/AboutPage/components/Member/Section/style.ts
Labels: size/L

#421 [Refactor] QA 반영
  src/assets/icons/ic_behance.svg
  src/lib/api/mock/about.ts
  src/lib/types/about.ts
  src/views/AboutPage/components/Member/Card/index.tsx
  src/views/AboutPage/components/Member/Section/index.tsx
  src/views/RecruitPage/components/Schedule/index.tsx
Labels: size/M

#427 [Chore] 기수 수정
  src/views/AboutPage/components/Record/Section/index.tsx
  src/views/RecruitPage/components/NotificationSection/index.tsx
Labels: size/XS

#428 [Refactor] 소개페이지 상단 배너 로딩 속도 개선
  .github/workflows/ci.yml
  src/pages/about.tsx
  src/views/AboutPage/components/Banner/index.tsx
  src/views/AboutPage/components/Banner/style.ts
Labels: size/S
