Repository sopt-makers/sopt.org-frontend, pull requests merged in 2024-01, with the labels that each got.

#349 [SP4] 후원탭 개선작업
  src/views/SponsorPage/components/CorporateJob/FieldTabs/index.tsx
  src/views/SponsorPage/components/CorporateJob/FieldTabs/style.ts
  src/views/SponsorPage/components/CorporateJob/JobPostings/index.tsx
  src/views/SponsorPage/components/CorporateJob/JobPostings/style.ts
  src/views/SponsorPage/components/CorporateJob/index.tsx
  src/views/SponsorPage/components/CorporateJob/style.ts
  src/views/SponsorPage/components/CorporateLinkedActivities/constants.ts
  src/views/SponsorPage/components/CorporateLinkedActivities/corporate-linked-activities.module.scss
  src/views/SponsorPage/components/CorporateLinkedActivities/index.tsx
  src/views/SponsorPage/components/CorporatePartner/corporate-partner.module.scss
  src/views/SponsorPage/components/CorporatePartner/index.tsx
  src/views/SponsorPage/components/CorporatePartner/style.ts
  src/views/SponsorPage/components/index.ts
  src/views/SponsorPage/index.tsx
Labels: size/XXL

#355 [SP4] 알림신청 정규식 패턴 수정
  src/views/RecruitPage/components/NotificationSection/index.tsx
Labels: size/XS

#353 [SP4] 소개탭 하단 작업
  public/images/members/152.png
  public/images/members/174.png
  public/images/members/209.png
  public/images/members/246.png
  public/images/members/291.png
  public/images/members/354.png
  public/images/members/387.png
  public/images/members/408.png
  public/images/members/49.png
  public/images/members/57.png
  public/images/members/80.png
  src/assets/icons/ic_github.svg
  src/assets/icons/ic_linkedin.svg
  src/assets/icons/ic_school.svg
  src/lib/api/mock/about.ts
  src/lib/api/remote/about.ts
  src/lib/types/about.ts
  src/pages/about.tsx
  src/views/AboutPage/components/Member/Card/index.tsx
  src/views/AboutPage/components/Member/Card/style.ts
  src/views/AboutPage/components/Member/Content/index.tsx
  src/views/AboutPage/components/Member/Content/style.ts
  src/views/AboutPage/components/Member/Section/index.tsx
  src/views/AboutPage/components/Member/Section/style.ts
  src/views/AboutPage/components/Record/Item/index.tsx
  src/views/AboutPage/components/Record/Item/style.ts
  src/views/AboutPage/components/Record/List/index.tsx
  src/views/AboutPage/components/Record/List/style.ts
  src/views/AboutPage/components/Record/Section/index.tsx
  src/views/AboutPage/components/Record/Section/style.ts
  src/views/AboutPage/constant/emptyMembers.ts
  src/views/AboutPage/hooks/useFetchMemeber.ts
  src/views/AboutPage/hooks/useResponsiveMember.ts
Labels: size/XL
