Repository sopt-makers/sopt.org-frontend, pull requests merged in 2025-05, with the labels that each got.

#444 [FEAT] 블로그 탭 GUI 반영
  src/assets/icons/ic_chevron-down.svg
  src/assets/icons/ic_sort.svg
  src/assets/images/img_video.png
  src/components/common/Select/index.tsx
  src/components/common/Select/style.ts
  src/lib/constants/tabs.ts
  src/lib/types/blog.ts
  src/lib/types/main.ts
  src/views/BlogPage/components/BlogPostList/index.tsx
  src/views/BlogPage/components/BlogPostList/style.ts
  src/views/BlogPage/components/BlogTab/index.tsx
  src/views/BlogPage/components/BlogTab/style.ts
  src/views/BlogPage/components/BlogTab/types.ts
  src/views/BlogPage/components/OfficialVideo/index.tsx
  src/views/BlogPage/components/OfficialVideo/style.ts
  src/views/BlogPage/index.tsx
Labels: feat, size/XL

#452 [FEAT] SOPT 이야기 공식 영상 연결
  package.json
  pnpm-lock.yaml
  src/views/BlogPage/components/OfficialVideo/index.tsx
  src/views/BlogPage/components/OfficialVideo/style.ts
Labels: size/M

#453 [FEAT] 블로그 탭 상단 배너 이미지 추가
  src/assets/images/img_review_banner.png
  src/assets/images/img_review_banner_mobile.png
  src/assets/images/img_review_banner_responsive.png
  src/assets/images/img_review_banner_tablet.png
  src/assets/images/img_story_banner.png
  src/assets/images/img_story_banner_mobile.png
  src/assets/images/img_story_banner_responsive.png
  src/assets/images/img_story_banner_tablet.png
  src/views/BlogPage/components/Banner/index.tsx
  src/views/BlogPage/components/Banner/style.ts
  src/views/BlogPage/components/BlogTab/style.ts
  src/views/BlogPage/index.tsx
Labels: feat, size/L

#457 [FEAT] 블로그 QA 해결
  src/components/Footer/OriginFooter/style.ts
  src/components/Layout/index.tsx
  src/components/common/Select/index.tsx
  src/lib/constants/tabs.ts
  src/lib/types/blog.ts
  src/views/BlogPage/components/BlogPost/DefaultProfileImage/index.tsx
  src/views/BlogPage/components/BlogPost/Header/index.tsx
  src/views/BlogPage/components/BlogPost/Header/style.ts
  src/views/BlogPage/components/BlogPost/index.tsx
  src/views/BlogPage/components/BlogPostList/index.tsx
  src/views/BlogPage/components/EmptyBlogPostList/index.tsx
  src/views/BlogPage/index.tsx
  src/views/RecruitPage/components/ActivityReview/index.tsx
Labels: bug, size/L

#456 [Fix] sp1 blog qa 사항 반영
  pnpm-lock.yaml
  src/components/common/Select/style.ts
  src/views/BlogPage/components/BlogTab/style.ts
Labels: feat, size/S
